import { FanficWork } from '../types';

export const coChanNhan: FanficWork = {
  id: 'co-chan-nhan',
  title: 'Cổ Chân Nhân',
  description: 'Phương Nguyên, một ma đầu trọng sinh, bất chấp tất cả để đạt được sự trường sinh.',
  country: 'Trung',
  plot: 'Phương Nguyên là một ma đầu sống 500 năm, sau khi bị vây giết đã sử dụng Xuân Thu Thiền để trọng sinh về thời niên thiếu. Với kiến thức từ kiếp trước và tâm tính tàn nhẫn, anh bắt đầu lại con đường tu luyện, lợi dụng mọi người và mọi thứ để đạt được mục tiêu tối thượng: Trường Sinh.',
  worldSetting: 'Thế giới của Cổ (Gu) - những sinh vật huyền bí mang lại sức mạnh. Tu luyện giả sử dụng Cổ để chiến đấu và thăng cấp. Thế giới vô cùng tàn khốc, nơi đạo đức là thứ xa xỉ và lợi ích là trên hết.',
  characters: [
    { name: 'Phương Nguyên', role: 'Nhân vật chính', age: '15 (500)', description: 'Ma đầu tàn nhẫn, lý trí tuyệt đối, không có giới hạn đạo đức, chỉ quan tâm đến lợi ích và trường sinh. Sở hữu Xuân Thu Thiền.' },
    { name: 'Phương Chính', role: 'Đối thủ / Anh em', age: '15', description: 'Em trai của Phương Nguyên, thiên tài với tư chất cao nhưng tâm tính non nớt, sau này trở thành quân cờ của Thiên Đình.' },
    { name: 'Bạch Ngưng Băng', role: 'Bạn đồng hành / Đối thủ', age: '16', description: 'Thiên tài của Bạch gia, mang trong mình Bắc Minh Băng Phách Thể, tính cách điên cuồng, sau bị Phương Nguyên biến thành nữ giới.' },
    { name: 'Thái Bạch Vân Sinh', role: 'Hỗ trợ', age: '60', description: 'Một cổ sư nhân hậu, sở hữu cổ trùng thời gian quý hiếm, là một trong số ít người đi theo Phương Nguyên lâu dài.' },
    { name: 'Hắc Lâu Lan', role: 'Hỗ trợ / Đối thủ', age: '20', description: 'Nữ kiêu hùng của Hắc gia, mang Đại Lực Chân Vũ Thể, mạnh mẽ và tham vọng, hợp tác với Phương Nguyên để báo thù.' },
    { name: 'Phượng Kim Hoàng', role: 'Đối thủ', age: '18', description: 'Thiên tài của Linh Duyên Trai, con gái của Phượng Cửu Ca, sở hữu mộng đạo truyền thừa và là tôn giả tương lai.' },
    { name: 'Thương Tâm Từ', role: 'Đồng minh', age: '18', description: 'Thiên kim tiểu thư của Thương gia, người mang ơn và luôn dành tình cảm đặc biệt cho Phương Nguyên, sau trở thành gia chủ Thương gia.' },
    { name: 'Tuyết Nhi', role: 'Đồng minh', age: '19', description: 'Tộc nhân Tuyết Dân, có hôn ước với Phương Nguyên, đại diện cho sự hợp tác giữa anh và các dị nhân.' },
    { name: 'Cổ Nguyệt Nhất Thế', role: 'Phản diện', age: '1000+', description: 'Tổ tiên của Cổ Nguyệt gia tộc, một cương thi cổ sư âm mưu huyết tế toàn bộ tộc nhân để hồi sinh.' },
    { name: 'Phượng Cửu Ca', role: 'Nhân vật quan trọng', age: '40+', description: 'Thiên tài âm đạo, cha của Phượng Kim Hoàng, một người có phong thái vô địch và đạo tâm kiên định.' },
    { name: 'Tử Vi Tiên Tử', role: 'Phản diện', age: '1000+', description: 'Trí đạo đại năng của Thiên Đình, luôn tìm cách tính kế và tiêu diệt Phương Nguyên để bảo vệ vận mệnh.' },
    { name: 'Long Công', role: 'Phản diện', age: '10000+', description: 'Hộ đạo nhân của tôn giả, một thực thể cực mạnh của Thiên Đình, biểu tượng của sự hy sinh và lòng trung thành.' },
    { name: 'Mặc Dao', role: 'Nhân vật quan trọng', age: '???', description: 'Ý chí của một vị luyện đạo tông sư, từng ẩn nấp trong tâm trí Phương Nguyên và dạy cho anh nhiều kiến thức quý giá.' },
    { name: 'Cự Dương Tiên Tôn', role: 'Tôn giả', age: '???', description: 'Người sáng lập vận đạo, để lại nhiều truyền thừa và âm mưu ảnh hưởng sâu sắc đến thế giới cổ sư.' },
    { name: 'U Hồn Ma Tôn', role: 'Tôn giả', age: '???', description: 'Người sáng lập hồn đạo, kẻ đã tạo ra Chí Tôn Tiên Thai Cổ mà Phương Nguyên đã cướp mất.' },
    { name: 'Hồng Liên Tiên Tôn', role: 'Tôn giả', age: '???', description: 'Người đã phá hủy túc mệnh cổ, tạo ra cơ hội cho những kẻ như Phương Nguyên thay đổi vận mệnh.' },
    { name: 'Túc Mệnh Cổ', role: 'Thực thể', age: 'Vĩnh cửu', description: 'Cổ trùng thiên địa sinh ra, chi phối vận mệnh của mọi sinh linh, là mục tiêu phá hủy của Phương Nguyên.' },
    { name: 'Tả Dạ Hôi', role: 'Hung thú', age: '???', description: 'Thái cổ hung thú cấp bậc cửu chuyển, mang lại tai họa và sự hủy diệt mỗi khi xuất hiện.' },
    { name: 'Lê Sơn Tiên Tử', role: 'Đồng minh', age: '40+', description: 'Dì của Hắc Lâu Lan, một cổ tiên trí đạo giỏi giao thiệp và là đồng minh tin cậy của Phương Nguyên ở Bắc Nguyên.' },
    { name: 'Tạ Hàm Vi', role: 'Đồng minh', age: '20', description: 'Nữ cổ sư nhân hậu ở Nam Cương, người đã giúp đỡ Phương Nguyên trong giai đoạn anh đóng giả làm tán tu.' },
    { name: 'Phượng Kim Hoàng', role: 'Đối thủ', age: '18', description: 'Thiên tài của Linh Duyên Trai, con gái của Phượng Cửu Ca, sở hữu mộng đạo truyền thừa và là tôn giả tương lai.' },
    { name: 'Hắc Lâu Lan', role: 'Hỗ trợ / Đối thủ', age: '20', description: 'Nữ kiêu hùng của Hắc gia, mang Đại Lực Chân Vũ Thể, mạnh mẽ và tham vọng, hợp tác với Phương Nguyên để báo thù.' },
    { name: 'Thái Bạch Vân Sinh', role: 'Hỗ trợ', age: '60', description: 'Một cổ sư nhân hậu, sở hữu cổ trùng thời gian quý hiếm, là một trong số ít người đi theo Phương Nguyên lâu dài.' },
    { name: 'Lâu Lan', role: 'Hỗ trợ', age: '20', description: 'Tên khác của Hắc Lâu Lan khi cải trang, một chiến binh mạnh mẽ ở Bắc Nguyên.' },
    { name: 'Cổ Nguyệt Phương Chính', role: 'Đối thủ', age: '15', description: 'Tên đầy đủ của em trai Phương Nguyên, người luôn sống dưới bóng của anh trai mình.' },
    { name: 'Bạch Thỏ', role: 'Hỗ trợ', age: '18', description: 'Một nữ cổ sư ở Nghĩa Bang, sau này trở thành thuộc hạ trung thành của Phương Nguyên.' },
    { name: 'Diệu Âm Tiên Tử', role: 'Hỗ trợ', age: '25', description: 'Một tán tu ở Nam Cương, sở hữu âm đạo mạnh mẽ, gia nhập phe Phương Nguyên sau khi bị anh thu phục.' },
    { name: 'Ảnh Vô Tà', role: 'Đối thủ / Đồng minh', age: '???', description: 'Phân thân của U Hồn Ma Tôn, sở hữu Dẫn Hồn Nhập Mộng, từng là kẻ thù không đội trời chung với Phương Nguyên.' },
    { name: 'Mao Thập Nhị', role: 'Đồng minh', age: '???', description: 'Một Mao Dân ở Lang Gia phúc địa, chuyên về luyện đạo và là trợ thủ đắc lực của Phương Nguyên.' },
    { name: 'Lang Gia Địa Linh', role: 'Đồng minh', age: '???', description: 'Địa linh của Lang Gia phúc địa, một luyện đạo tông sư sở hữu vô số cổ trùng và truyền thừa quý giá.' },
    { name: 'Tần Đỉnh Lăng', role: 'Phản diện', age: '1000+', description: 'Cường giả vận đạo của Thiên Đình, người đã thức tỉnh để đối phó với Phương Nguyên.' },
    { name: 'Võ Cơ Hoàng', role: 'Đối thủ', age: '???', description: 'Cường giả của Võ gia ở Nam Cương, một người chính trực nhưng luôn bị Phương Nguyên tính kế.' }
  ]
};
