import { FanficWork } from '../types';

export const daiDaoTrieuThien: FanficWork = {
  id: 'dai-dao-trieu-thien',
  title: 'Đại Đạo Triều Thiên',
  description: 'Tỉnh Cửu, một thiếu niên bí ẩn với vẻ đẹp tuyệt thế, bắt đầu hành trình tu đạo đầy tiêu sái và bí ẩn tại Thanh Sơn Tông.',
  country: 'Trung',
  plot: 'Tỉnh Cửu xuất hiện tại Thanh Sơn Tông với thân phận một đệ tử bình thường nhưng lại sở hữu kiến thức và phong thái của một vị đại năng. Anh lười biếng, chỉ thích nằm phơi nắng nhưng mỗi khi ra tay đều chấn động thiên hạ. Hành trình của anh là quá trình tìm kiếm chân lý của đại đạo và giải mã những bí ẩn về thân thế của chính mình.',
  worldSetting: 'Thế giới tu tiên mang phong cách cổ điển, thanh tao. Các tông môn tu luyện dựa trên kiếm đạo và đạo pháp tự nhiên.',
  characters: [
    { name: 'Tỉnh Cửu', role: 'Nhân vật chính', age: '16 (1000+)', description: 'Lười biếng, xinh đẹp tuyệt trần, sở hữu kiếm đạo vô song và phong thái tiêu sái. Thực chất là Cảnh Dương chân nhân trọng sinh.' },
    { name: 'Triệu Táp Nguyệt', role: 'Nữ chính / Đồng minh', age: '18', description: 'Nữ đệ tử tài năng của Thanh Sơn Tông, tính cách mạnh mẽ, thẳng thắn và luôn đồng hành cùng Tỉnh Cửu. Sau trở thành đỉnh chủ Thần Mạt Phong.' },
    { name: 'Liễu Thập Tuế', role: 'Đồng minh', age: '15', description: 'Đệ tử trung thành của Tỉnh Cửu, thật thà, chất phác và có nghị lực phi thường. Cậu đã trải qua nhiều gian khổ để chứng minh lòng trung thành.' },
    { name: 'Cố Thanh', role: 'Đồng minh', age: '17', description: 'Đệ tử của Tỉnh Cửu, thông minh, điềm tĩnh và là người quản lý mọi công việc sự vụ cho Thần Mạt Phong.' },
    { name: 'Liên Tam Nguyệt', role: 'Đồng minh', age: '1000+', description: 'Một vị đại năng của Thủy Nguyệt Am, xinh đẹp và mạnh mẽ, có mối tình sâu đậm với Cảnh Dương chân nhân.' },
    { name: 'Thanh Sơn Chưởng Môn', role: 'Thủ lĩnh', age: '100+', description: 'Người đứng đầu Thanh Sơn Tông, thực chất là sư điệt của Tỉnh Cửu, luôn âm thầm bảo vệ sư thúc của mình.' },
    { name: 'Nam Vong', role: 'Đồng minh', age: '30+', description: 'Đỉnh chủ Thanh Dung Phong, tính cách hào sảng, thích uống rượu và rất quan tâm đến Tỉnh Cửu theo cách riêng.' },
    { name: 'Nguyên Khúc', role: 'Đồng minh', age: '16', description: 'Đệ tử trẻ tuổi của Thanh Sơn Tông, có thiên phú kiếm đạo và rất ngưỡng mộ Tỉnh Cửu.' },
    { name: 'Trác Như Tuế', role: 'Đối thủ / Đồng minh', age: '19', description: 'Thiên tài kiếm đạo lười biếng của Thiên Thủy Phong, luôn coi Tỉnh Cửu là mục tiêu để vượt qua nhưng cũng rất tôn trọng anh.' },
    { name: 'Thi Cửu', role: 'Phản diện', age: '1000+', description: 'Một thực thể cổ xưa mang theo hận thù và âm mưu nhắm vào Tỉnh Cửu và Thanh Sơn Tông.' },
    { name: 'Bạch Sớm', role: 'Đối thủ / Đồng minh', age: '18', description: 'Thiên tài của Trung Châu Phái, sở hữu vẻ đẹp và tài năng không kém Triệu Táp Nguyệt, có mối quan hệ phức tạp với Tỉnh Cửu.' },
    { name: 'Đường Nguyên', role: 'Đồng minh', age: '20', description: 'Đệ tử của Trung Châu Phái, tính cách ôn hòa, thường xuyên giao lưu với các đệ tử Thanh Sơn.' },
    { name: 'Tào Viên', role: 'Đồng minh', age: '40+', description: 'Đao khách mạnh nhất thế gian, người trấn giữ biên thùy chống lại quái vật Tuyết Nguyên, một bậc đại trượng phu.' },
    { name: 'Tây Hải Kiếm Thần', role: 'Phản diện', age: '100+', description: 'Một trong những cường giả mạnh nhất thế giới, tham vọng thống nhất kiếm đạo và là đối thủ lớn của Thanh Sơn.' },
    { name: 'Âm Tam', role: 'Phản diện', age: '1000+', description: 'Cựu chưởng môn Thanh Sơn, sư huynh của Cảnh Dương, một kẻ mưu mô xảo quyệt luôn tìm cách quay lại nắm quyền.' },
    { name: 'Tô Tử Kính', role: 'Đồng minh', age: '???', description: 'Một vị tiền bối ẩn cư, có kiến thức uyên bác về lịch sử và các bí mật của giới tu tiên.' },
    { name: 'Tuyết Cơ', role: 'Thực thể tối cao', age: '???', description: 'Nữ vương của Tuyết Nguyên, một thực thể mạnh mẽ đến mức không ai dám đối đầu, có mối liên hệ kỳ lạ với Tỉnh Cửu.' },
    { name: 'Lưu Thập Tuế', role: 'Đồng minh', age: '15', description: 'Tên thật là Liễu Thập Tuế, người luôn sát cánh bên Tỉnh Cửu từ những ngày đầu ở thôn quê.' },
    { name: 'Quốc Sư', role: 'Nhân vật quan trọng', age: '50+', description: 'Người đứng đầu triều đình, luôn cố gắng cân bằng thế lực giữa các tông môn và bảo vệ dân chúng.' },
    { name: 'Thanh Nhàn', role: 'Đồng minh', age: '???', description: 'Một đệ tử của Thủy Nguyệt Am, bạn thân của Triệu Táp Nguyệt.' },
    { name: 'Thanh Điểu', role: 'Linh thú', age: '???', description: 'Linh điểu của Thanh Sơn Tông, người bạn đồng hành trung thành của Tỉnh Cửu.' },
    { name: 'Bạch Vân', role: 'Đồng minh', age: '???', description: 'Đệ tử của Trung Châu Phái, một người có tâm tính thiện lương.' },
    { name: 'Lưu A', role: 'Đối thủ', age: '???', description: 'Một kiếm khách tài ba của Tây Hải, luôn tìm cách thách thức các đệ tử Thanh Sơn.' },
    { name: 'Tô Tử Kính', role: 'Đồng minh', age: '???', description: 'Một vị tiền bối ẩn cư, có kiến thức uyên bác về lịch sử và các bí mật của giới tu tiên.' },
    { name: 'Đường Nguyên', role: 'Đồng minh', age: '20', description: 'Đệ tử của Trung Châu Phái, tính cách ôn hòa, thường xuyên giao lưu với các đệ tử Thanh Sơn.' },
    { name: 'Nguyên Khúc', role: 'Đồng minh', age: '16', description: 'Đệ tử trẻ tuổi của Thanh Sơn Tông, có thiên phú kiếm đạo và rất ngưỡng mộ Tỉnh Cửu.' },
    { name: 'Cố Thanh', role: 'Đồng minh', age: '17', description: 'Đệ tử của Tỉnh Cửu, thông minh, điềm tĩnh và là người quản lý mọi công việc sự vụ cho Thần Mạt Phong.' },
    { name: 'Trác Như Tuế', role: 'Đối thủ / Đồng minh', age: '19', description: 'Thiên tài kiếm đạo lười biếng của Thiên Thủy Phong, luôn coi Tỉnh Cửu là mục tiêu để vượt qua nhưng cũng rất tôn trọng anh.' },
    { name: 'Nam Vong', role: 'Đồng minh', age: '30+', description: 'Đỉnh chủ Thanh Dung Phong, tính cách hào sảng, thích uống rượu và rất quan tâm đến Tỉnh Cửu theo cách riêng.' },
    { name: 'Tỉnh Lân', role: 'Gia đình', age: '18', description: 'Anh trai của Tỉnh Cửu ở kiếp này, một người bình thường nhưng luôn yêu thương em trai.' },
    { name: 'Thanh Lương', role: 'Đồng minh', age: '???', description: 'Đệ tử của Thủy Nguyệt Am, người luôn hỗ trợ Triệu Táp Nguyệt.' },
    { name: 'Bạch Sớm', role: 'Đối thủ / Đồng minh', age: '18', description: 'Thiên tài của Trung Châu Phái, sở hữu vẻ đẹp và tài năng không kém Triệu Táp Nguyệt, có mối quan hệ phức tạp với Tỉnh Cửu.' }
  ]
};
