import { FanficWork } from '../types';

export const daiPhungDaCanhNhan: FanficWork = {
  id: 'dai-phung-da-canh-nhan',
  title: 'Đại Phụng Đả Canh Nhân',
  description: 'Hứa Thất An, một cảnh sát hiện đại xuyên không về triều đại Đại Phụng, dùng kiến thức phá án để khuấy đảo giới tu tiên và quan trường.',
  country: 'Trung',
  plot: 'Hứa Thất An vốn là một cảnh sát, sau khi chết vì ngộ độc rượu đã xuyên không về thế giới tu tiên, trở thành một bổ khoái của huyện nha. Với tư duy phá án hiện đại và sự giúp đỡ của một hệ thống bí ẩn, anh dần thăng tiến trong hàng ngũ Đả Canh Nhân - tổ chức tình báo và giám sát của triều đình, đồng thời khám phá ra những âm mưu kinh thiên động địa liên quan đến vận mệnh quốc gia.',
  worldSetting: 'Thế giới tiên hiệp kết hợp trinh thám và quan trường. Hệ thống tu luyện đa dạng: Võ phu, Nho gia, Đạo gia, Phật gia, Vu sư, Yêu tộc... Mỗi hệ thống có những quy tắc và sức mạnh riêng biệt.',
  characters: [
    { name: 'Hứa Thất An', role: 'Nhân vật chính', age: '20', description: 'Cảnh sát hiện đại xuyên không, thông minh, lém lỉnh, giỏi phá án, sở hữu vận may cực lớn và nhiều bí mật kinh thiên. Anh là một Võ phu cấp cao.' },
    { name: 'Ngụy Uyên', role: 'Người dẫn dắt', age: '45', description: 'Đứng đầu Đả Canh Nhân, một đại nho và là một nhà quân sự lỗi lạc, người thầy dẫn dắt Hứa Thất An. Ông là một người cực kỳ thâm trầm.' },
    { name: 'Hoài Khánh Công Chúa', role: 'Nữ chính / Đồng minh', age: '22', description: 'Công chúa của Đại Phụng, cực kỳ thông minh, lạnh lùng và có tham vọng chính trị lớn. Sau này trở thành Nữ đế.' },
    { name: 'Lâm An Công Chúa', role: 'Nữ chính', age: '19', description: 'Em gái của Hoài Khánh, tính cách ngây thơ, hoạt bát và rất yêu mến Hứa Thất An. Cô là người mang lại sự ấm áp cho anh.' },
    { name: 'Lý Diệu Chân', role: 'Đồng minh', age: '21', description: 'Thánh nữ của Thiên Tông, tính cách hiệp nghĩa, thích hành hiệp trượng nghĩa và là bạn đồng hành của Hứa Thất An.' },
    { name: 'Hứa Tân Niên', role: 'Anh em', age: '18', description: 'Em họ của Hứa Thất An, một thiên tài Nho gia, tính cách kiêu ngạo nhưng rất kính trọng anh trai.' },
    { name: 'Hứa Linh Nguyệt', role: 'Gia đình', age: '16', description: 'Em gái của Hứa Thất An, xinh đẹp, dịu dàng nhưng bên trong rất thông minh và có phần "bụng đen".' },
    { name: 'Hứa Linh Âm', role: 'Gia đình', age: '6', description: 'Em út của Hứa Thất An, một cô bé ham ăn, ngây thơ nhưng sở hữu thiên phú về cổ thuật và sức mạnh thể chất.' },
    { name: 'Thải Vi', role: 'Đồng minh', age: '18', description: 'Đệ tử của Giám Chính, tính cách ngây ngô, ham ăn và rất giỏi về luyện kim thuật.' },
    { name: 'Chung Ly', role: 'Đồng minh', age: '20', description: 'Đệ tử của Giám Chính, luôn gặp xui xẻo nên phải che mặt, có mối quan hệ đặc biệt với Hứa Thất An.' },
    { name: 'Giám Chính', role: 'Thực thể tối cao', age: '1000+', description: 'Người bảo hộ của Đại Phụng, đứng đầu Khâm Thiên Giám, một thực thể thần bí chi phối vận mệnh quốc gia.' },
    { name: 'Lạc Ngọc Hành', role: 'Nữ chính', age: '30+', description: 'Quốc sư của Đại Phụng, lãnh đạo Nhân Tông, xinh đẹp tuyệt trần và đang phải đối mặt với nghiệp lực.' },
    { name: 'Lý Linh Tố', role: 'Đồng minh', age: '22', description: 'Thánh tử của Thiên Tông, một kẻ đào hoa, phong lưu nhưng rất nghĩa khí, bạn thân của Hứa Thất An.' },
    { name: 'Kim Liên Đạo Trưởng', role: 'Người dẫn dắt', age: '???', description: 'Lãnh đạo của Địa Tông, người đã lập ra Thiên Địa Hội và dẫn dắt các thành viên chống lại sự sa đọa.' },
    { name: 'A Tô La', role: 'Đồng minh', age: '???', description: 'Một cường giả Phật môn, sau này gia nhập phe của Hứa Thất An để chống lại những âm mưu của Tây Phương.' },
    { name: 'Cửu Vĩ Thiên Hồ', role: 'Nữ chính', age: '1000+', description: 'Nữ vương của Yêu tộc, quyến rũ và đầy quyền năng, có mối quan hệ hợp tác và tình cảm phức tạp với Hứa Thất An.' },
    { name: 'Nguyên Cảnh Đế', role: 'Phản diện', age: '50+', description: 'Hoàng đế của Đại Phụng, một kẻ đa nghi, tàn nhẫn và bị ám ảnh bởi sự trường sinh bất tử.' },
    { name: 'Trấn Bắc Vương', role: 'Phản diện', age: '45', description: 'Em trai của hoàng đế, một võ phu cấp cao tàn bạo, kẻ đã gây ra thảm sát để luyện hóa huyết đan.' },
    { name: 'Hứa Nhị Thúc', role: 'Gia đình', age: '42', description: 'Cha của Hứa Tân Niên, một võ quan trung hậu, luôn yêu thương và bảo vệ gia đình.' },
    { name: 'Thẩm Thẩm', role: 'Gia đình', age: '38', description: 'Mẹ của Hứa Tân Niên, tính cách đanh đá nhưng thực chất rất quan tâm đến Hứa Thất An.' },
    { name: 'Dương Thiên Huyễn', role: 'Đồng minh', age: '25', description: 'Đệ tử của Giám Chính, một thiên tài luyện kim thuật luôn thích "làm màu" và có những phát minh kỳ quặc.' },
    { name: 'Lý Linh Tố', role: 'Đồng minh', age: '22', description: 'Thánh tử của Thiên Tông, một kẻ đào hoa, phong lưu nhưng rất nghĩa khí, bạn thân của Hứa Thất An.' },
    { name: 'Sở Nguyên Đề', role: 'Đồng minh', age: '28', description: 'Một kiếm khách tài ba, thành viên của Thiên Địa Hội, người luôn âm thầm hỗ trợ Hứa Thất An.' },
    { name: 'Hằng Viễn', role: 'Đồng minh', age: '30', description: 'Một hòa thượng nhân hậu, võ phu cấp cao, thành viên của Thiên Địa Hội.' },
    { name: 'Lạc Ngọc Hành', role: 'Nữ chính', age: '30+', description: 'Quốc sư của Đại Phụng, lãnh đạo Nhân Tông, xinh đẹp tuyệt trần và đang phải đối mặt với nghiệp lực.' },
    { name: 'Giám Chính', role: 'Thực thể tối cao', age: '1000+', description: 'Người bảo hộ của Đại Phụng, đứng đầu Khâm Thiên Giám, một thực thể thần bí chi phối vận mệnh quốc gia.' },
    { name: 'Chung Ly', role: 'Đồng minh', age: '20', description: 'Đệ tử của Giám Chính, luôn gặp xui xẻo nên phải che mặt, có mối quan hệ đặc biệt với Hứa Thất An.' },
    { name: 'Thải Vi', role: 'Đồng minh', age: '18', description: 'Đệ tử của Giám Chính, tính cách ngây ngô, ham ăn và rất giỏi về luyện kim thuật.' },
    { name: 'Hứa Linh Âm', role: 'Gia đình', age: '6', description: 'Em út của Hứa Thất An, một cô bé ham ăn, ngây thơ nhưng sở hữu thiên phú về cổ thuật và sức mạnh thể chất.' },
    { name: 'Hứa Linh Nguyệt', role: 'Gia đình', age: '16', description: 'Em gái của Hứa Thất An, xinh đẹp, dịu dàng nhưng bên trong rất thông minh và có phần "bụng đen".' },
    { name: 'Hứa Tân Niên', role: 'Anh em', age: '18', description: 'Em họ của Hứa Thất An, một thiên tài Nho gia, tính cách kiêu ngạo nhưng rất kính trọng anh trai.' },
    { name: 'Lý Diệu Chân', role: 'Đồng minh', age: '21', description: 'Thánh nữ của Thiên Tông, tính cách hiệp nghĩa, thích hành hiệp trượng nghĩa và là bạn đồng hành của Hứa Thất An.' },
    { name: 'Lâm An Công Chúa', role: 'Nữ chính', age: '19', description: 'Em gái của Hoài Khánh, tính cách ngây thơ, hoạt bát và rất yêu mến Hứa Thất An. Cô là người mang lại sự ấm áp cho anh.' },
    { name: 'Hoài Khánh Công Chúa', role: 'Nữ chính / Đồng minh', age: '22', description: 'Công chúa của Đại Phụng, cực kỳ thông minh, lạnh lùng và có tham vọng chính trị lớn. Sau này trở thành Nữ đế.' },
    { name: 'Ngụy Uyên', role: 'Người dẫn dắt', age: '45', description: 'Đứng đầu Đả Canh Nhân, một đại nho và là một nhà quân sự lỗi lạc, người thầy dẫn dắt Hứa Thất An. Ông là một người cực kỳ thâm trầm.' },
    { name: 'Hứa Nhị Thúc', role: 'Gia đình', age: '42', description: 'Cha của Hứa Tân Niên, một võ quan trung hậu, luôn yêu thương và bảo vệ gia đình.' },
    { name: 'Trấn Bắc Vương', role: 'Phản diện', age: '45', description: 'Em trai của hoàng đế, một võ phu cấp cao tàn bạo, kẻ đã gây ra thảm sát để luyện hóa huyết đan.' },
    { name: 'Nguyên Cảnh Đế', role: 'Phản diện', age: '50+', description: 'Hoàng đế của Đại Phụng, một kẻ đa nghi, tàn nhẫn và bị ám ảnh bởi sự trường sinh bất tử.' },
    { name: 'Cửu Vĩ Thiên Hồ', role: 'Nữ chính', age: '1000+', description: 'Nữ vương của Yêu tộc, quyến rũ và đầy quyền năng, có mối quan hệ hợp tác và tình cảm phức tạp với Hứa Thất An.' },
    { name: 'A Tô La', role: 'Đồng minh', age: '???', description: 'Một cường giả Phật môn, sau này gia nhập phe của Hứa Thất An để chống lại những âm mưu của Tây Phương.' },
    { name: 'Kim Liên Đạo Trưởng', role: 'Người dẫn dắt', age: '???', description: 'Lãnh đạo của Địa Tông, người đã lập ra Thiên Địa Hội và dẫn dắt các thành viên chống lại sự sa đọa.' },
    { name: 'Thánh Tử', role: 'Đồng minh', age: '22', description: 'Tên khác của Lý Linh Tố, người luôn sát cánh bên Hứa Thất An trong các cuộc phiêu lưu.' },
    { name: 'Tống Đình Phong', role: 'Đồng minh', age: '25', description: 'Đồng nghiệp của Hứa Thất An ở Đả Canh Nhân, một người bạn trung thành và hài hước.' },
    { name: 'Chu Quảng Hiếu', role: 'Đồng minh', age: '25', description: 'Đồng nghiệp của Hứa Thất An ở Đả Canh Nhân, trầm tính và đáng tin cậy.' }
  ]
};
