
import { FanficWork } from '../types';

export const dauYemThan: FanficWork = {
  id: 'dau_yem_than',
  title: 'Đấu Yếm Thần',
  description: 'Thế giới nơi con người chiến đấu bằng các bộ Yếm Giáp thần bí. Lục Trần vô tình sở hữu Yếm Giáp của các vị thần cổ đại, bắt đầu hành trình phá giải bí mật về sự sụp đổ của các vị thần.',
  country: 'Trung',
  characters: [
    { name: 'Lục Trần', role: 'Main Character', description: 'Người sở hữu Yếm Giáp Thần Cấp, có khả năng triệu hoán sức mạnh của các vị thần cổ đại. Tính cách điềm tĩnh, mưu lược và quyết đoán.' },
    { name: 'Thần Yếm Ý Chí', role: 'Thực thể hướng dẫn', description: 'Ý chí của bộ Yếm Giáp cổ đại, cung cấp kiến thức và sức mạnh cho Lục Trần.' },
    { name: 'Lâm Tuyết', role: 'Nữ chính (Chiến binh)', description: 'Thiên tài sử dụng Yếm Giáp, bạn đồng hành và là người yêu của Lục Trần.' },
    { name: 'Vương Đại Lực', role: 'Bạn thân (Hỗ trợ)', description: 'Chuyên gia về vật liệu và rèn đúc Yếm Giáp, luôn hỗ trợ Lục Trần.' },
    { name: 'Diệp Linh', role: 'Nữ đặc vụ (Hội Đồng)', description: 'Người giám sát Lục Trần, ban đầu nghi ngờ sau đó trở thành đồng minh.' },
    { name: 'Hắc Y Nhân', role: 'Kẻ thù bí ẩn (Ma Giáo)', description: 'Thành viên của tổ chức muốn lợi dụng Yếm Giáp để hồi sinh Ma Thần.' },
    { name: 'Lý Thanh', role: 'Nhà khảo cổ (Yếm Giáp)', description: 'Người nghiên cứu về lịch sử và nguồn gốc của các bộ Yếm Giáp cổ đại.' },
    { name: 'Triệu Linh', role: 'Nữ bác sĩ (Linh y)', description: 'Chuyên gia chữa trị các vết thương linh hồn và cơ thể cho các chiến binh.' },
    { name: 'Mục Thiết', role: 'Đối thủ (Gia tộc lớn)', description: 'Người sở hữu Yếm Giáp của các gia tộc quyền lực, luôn muốn so tài với Lục Trần.' },
    { name: 'Tần gia chủ', role: 'Thế lực tài phiệt', description: 'Người nắm giữ nguồn tài nguyên Linh Thạch khổng lồ để duy trì Yếm Giáp.' },
    { name: 'Hàn Sương', role: 'Nữ chiến binh (Lạnh lùng)', description: 'Tốc độ và sự chính xác là vũ khí của cô trong các trận chiến Yếm Giáp.' },
    { name: 'Lục Hải', role: 'Cha Lục Trần', description: 'Nhà nghiên cứu mất tích, người đầu tiên khám phá ra bí mật về Yếm Thần.' },
    { name: 'Vương Hổ', role: 'Đội trưởng an ninh', description: 'Sức mạnh cơ bắp kết hợp với Yếm Giáp hạng nặng.' },
    { name: 'Chu Hải', role: 'Nhà thám hiểm di tích', description: 'Người thường xuyên đi vào các khu vực di tích cổ đại nguy hiểm.' },
    { name: 'Mã Lực', role: 'Chiến binh hệ lôi', description: 'Sức mạnh tấn công bùng nổ từ Yếm Giáp điện năng.' },
    { name: 'Hà Linh', role: 'Nữ y tá (Tâm linh)', description: 'Người có khả năng làm dịu sự hỗn loạn của linh hồn chiến binh.' },
    { name: 'Tôn Kiên', role: 'Chỉ huy quân đội', description: 'Người có trách nhiệm cao, bảo vệ thành phố khỏi sự tấn công của Ma Thú.' },
    { name: 'Lý Na', role: 'Phóng viên chiến trường', description: 'Luôn theo sát các trận chiến của Lục Trần.' },
    { name: 'Trương Ba', role: 'Chiến binh hệ độc', description: 'Cách chiến đấu quỷ dị, sử dụng Yếm Giáp ăn mòn.' },
    { name: 'Phạm Tiến', role: 'Nhà sưu tầm Yếm Giáp', description: 'Người sở hữu bộ sưu tập Yếm Giáp cổ đại khổng lồ.' },
    { name: 'Đỗ Quyên', role: 'Nữ chiến binh hệ hoa', description: 'Vẻ đẹp đi kèm với sự nguy hiểm từ Yếm Giáp sinh học.' },
    { name: 'Tạ Thiên', role: 'Thiên tài Yếm Giáp phương Bắc', description: 'Đối thủ lớn nhất của Lục Trần.' },
    { name: 'Lục Bình', role: 'Chiến binh hệ thủy', description: 'Khả năng khống chế Yếm Giáp chất lỏng.' },
    { name: 'Thần Yếm Ý Chí (Cổ đại)', role: 'Thực thể thần thánh', description: 'Ý chí của các vị thần, hướng dẫn Lục Trần đạt đến đỉnh cao.' },
    { name: 'Lục Trần (Tương lai)', role: 'Yếm Thần Chi Chủ', description: 'Hình ảnh Lục Trần khi đã làm chủ mọi Yếm Giáp của vũ trụ.' },
    { name: 'Tiểu Hắc', role: 'Linh thú hỗ trợ', description: 'Linh thú thông minh có khả năng phân tích điểm yếu của kẻ thù.' },
    { name: 'Bạch Lão', role: 'Người gác cổng di tích', description: 'Người canh giữ lối vào các vùng không gian cấm.' },
    { name: 'Thanh Nữ', role: 'Thực thể linh hồn', description: 'Cô gái được tạo ra từ năng lượng Yếm Giáp thuần khiết.' },
    { name: 'Hồng Ma', role: 'Kẻ hủy diệt di tích', description: 'Thực thể mang sức mạnh hỗn loạn.' },
    { name: 'Lam Thần', role: 'Người bảo hộ trật tự', description: 'Thực thể mang sức mạnh cân bằng.' },
    { name: 'Tử Vương', role: 'Kẻ thống trị hư vô', description: 'Thực thể mang sức mạnh bóng tối.' },
    { name: 'Kim Thánh', role: 'Người mang ánh sáng sáng tạo', description: 'Thực thể mang sức mạnh khởi nguyên.' },
    { name: 'Mộc Linh', role: 'Người mang sự sống', description: 'Thực thể mang sức mạnh sinh trưởng.' },
    { name: 'Thổ Đế', role: 'Người mang sự ổn định', description: 'Thực thể mang sức mạnh kiên cố.' },
    { name: 'Thủy Hậu', role: 'Người mang sự linh hoạt', description: 'Thực thể mang sức mạnh biến hóa.' },
    { name: 'Hỏa Quân', role: 'Người mang sự hủy diệt', description: 'Thực thể mang sức mạnh nhiệt năng.' },
    { name: 'Phong Tôn', role: 'Người mang sự tự do', description: 'Thực thể mang sức mạnh tốc độ.' },
    { name: 'Lôi Đế', role: 'Người mang sự phán xét', description: 'Thực thể mang sức mạnh uy áp.' },
    { name: 'Vô Danh', role: 'Kẻ lang thang', description: 'Người bí ẩn nắm giữ nhiều bí mật về Yếm Thần.' },
    { name: 'Lão Kiếm', role: 'Kiếm khách Yếm Giáp', description: 'Người sử dụng Yếm Giáp kết hợp với kiếm pháp đỉnh cao.' }
  ]
};
