
import { FanficWork } from '../types';

export const digimon: FanficWork = {
  id: 'digimon',
  title: 'Digimon (Thế Giới Kỹ Thuật Số)',
  description: 'Thế giới nơi các dữ liệu máy tính biến thành những sinh vật sống gọi là Digimon. Một nhóm trẻ em bị cuốn vào Thế Giới Kỹ Thuật Số, trở thành những Đứa Trẻ Được Chọn để bảo vệ cả hai thế giới.',
  country: 'Nhật',
  characters: [
    { name: 'Taichi Yagami', role: 'Main Character (Courage)', description: 'Lãnh đạo của nhóm, sở hữu Huy hiệu Dũng Khí. Đồng hành cùng Agumon.' },
    { name: 'Yamato Ishida', role: 'Đối thủ/Bạn thân (Friendship)', description: 'Người trầm tính, sở hữu Huy hiệu Tình Bạn. Đồng hành cùng Gabumon.' },
    { name: 'Sora Takenouchi', role: 'Thành viên (Love)', description: 'Cô gái mạnh mẽ, sở hữu Huy hiệu Tình Yêu. Đồng hành cùng Piyomon.' },
    { name: 'Koushiro Izumi', role: 'Trí tuệ (Knowledge)', description: 'Thiên tài máy tính, sở hữu Huy hiệu Tri Thức. Đồng hành cùng Tentomon.' },
    { name: 'Mimi Tachikawa', role: 'Thành viên (Purity)', description: 'Cô gái điệu đà nhưng chân thành, sở hữu Huy hiệu Tinh Khiết. Đồng hành cùng Palmon.' },
    { name: 'Joe Kido', role: 'Thành viên (Sincerity)', description: 'Người lớn tuổi nhất, sở hữu Huy hiệu Thành Thật. Đồng hành cùng Gomamon.' },
    { name: 'Takeru Takaishi', role: 'Thành viên (Hope)', description: 'Em trai Yamato, sở hữu Huy hiệu Hy Vọng. Đồng hành cùng Patamon.' },
    { name: 'Hikari Yagami', role: 'Thành viên (Light)', description: 'Em gái Taichi, sở hữu Huy hiệu Ánh Sáng. Đồng hành cùng Tailmon.' },
    { name: 'Agumon', role: 'Digimon đồng hành', description: 'Digimon hệ bò sát, có khả năng tiến hóa thành Greymon.' },
    { name: 'Gabumon', role: 'Digimon đồng hành', description: 'Digimon hệ thú, có khả năng tiến hóa thành Garurumon.' },
    { name: 'Piyomon', role: 'Digimon đồng hành', description: 'Digimon hệ chim, có khả năng tiến hóa thành Birdramon.' },
    { name: 'Tentomon', role: 'Digimon đồng hành', description: 'Digimon hệ côn trùng, có khả năng tiến hóa thành Kabuterimon.' },
    { name: 'Palmon', role: 'Digimon đồng hành', description: 'Digimon hệ thực vật, có khả năng tiến hóa thành Togemon.' },
    { name: 'Gomamon', role: 'Digimon đồng hành', description: 'Digimon hệ biển, có khả năng tiến hóa thành Ikkakumon.' },
    { name: 'Patamon', role: 'Digimon đồng hành', description: 'Digimon hệ thú bay, có khả năng tiến hóa thành Angemon.' },
    { name: 'Tailmon', role: 'Digimon đồng hành', description: 'Digimon hệ mèo, có khả năng tiến hóa thành Angewomon.' },
    { name: 'Daisuke Motomiya', role: 'Main Character (02)', description: 'Lãnh đạo thế hệ thứ hai, sở hữu Huy hiệu Dũng Khí và Tình Bạn. Đồng hành cùng V-mon.' },
    { name: 'Miyako Inoue', role: 'Thành viên (02)', description: 'Cô gái năng động, sở hữu Huy hiệu Tình Yêu và Tri Thức. Đồng hành cùng Hawkmon.' },
    { name: 'Iori Hida', role: 'Thành viên (02)', description: 'Cậu bé nghiêm túc, sở hữu Huy hiệu Thành Thật và Tri Thức. Đồng hành cùng Armadimon.' },
    { name: 'Ken Ichijouji', role: 'Đối thủ/Đồng đội (02)', description: 'Cựu Digimon Kaiser, sở hữu Huy hiệu Nhân Từ. Đồng hành cùng Wormmon.' },
    { name: 'V-mon', role: 'Digimon đồng hành (02)', description: 'Digimon hệ rồng nhỏ, có khả năng tiến hóa thành XV-mon.' },
    { name: 'Hawkmon', role: 'Digimon đồng hành (02)', description: 'Digimon hệ chim, có khả năng tiến hóa thành Aquilamon.' },
    { name: 'Armadimon', role: 'Digimon đồng hành (02)', description: 'Digimon hệ thú bọc giáp, có khả năng tiến hóa thành Ankylomon.' },
    { name: 'Wormmon', role: 'Digimon đồng hành (02)', description: 'Digimon hệ sâu bướm, có khả năng tiến hóa thành Stingmon.' },
    { name: 'Takato Matsuki', role: 'Main Character (Tamers)', description: 'Cậu bé yêu thích Digimon, tự tạo ra Guilmon.' },
    { name: 'Ruki Makino', role: 'Đối thủ/Đồng đội (Tamers)', description: 'Nữ hoàng Digimon, tính cách lạnh lùng. Đồng hành cùng Renamon.' },
    { name: 'Lee Jenrya', role: 'Thành viên (Tamers)', description: 'Cậu bé điềm tĩnh, sở hữu Terriermon.' },
    { name: 'Guilmon', role: 'Digimon đồng hành (Tamers)', description: 'Digimon hệ rồng đỏ, có khả năng tiến hóa thành Growmon.' },
    { name: 'Renamon', role: 'Digimon đồng hành (Tamers)', description: 'Digimon hệ cáo, có khả năng tiến hóa thành Kyubimon.' },
    { name: 'Terriermon', role: 'Digimon đồng hành (Tamers)', description: 'Digimon hệ thú nhỏ, có khả năng tiến hóa thành Galgomon.' },
    { name: 'Takuya Kanbara', role: 'Main Character (Frontier)', description: 'Cậu bé có khả năng biến hình thành Digimon hệ Lửa.' },
    { name: 'Koji Minamoto', role: 'Đối thủ/Đồng đội (Frontier)', description: 'Cậu bé có khả năng biến hình thành Digimon hệ Ánh Sáng.' },
    { name: 'Izumi Orimoto', role: 'Thành viên (Frontier)', description: 'Cô gái có khả năng biến hình thành Digimon hệ Gió.' },
    { name: 'Junpei Shibayama', role: 'Thành viên (Frontier)', description: 'Cậu bé có khả năng biến hình thành Digimon hệ Sấm Sét.' },
    { name: 'Tomoki Himi', role: 'Thành viên (Frontier)', description: 'Cậu bé có khả năng biến hình thành Digimon hệ Băng.' },
    { name: 'Koichi Kimura', role: 'Thành viên (Frontier)', description: 'Anh trai Koji, có khả năng biến hình thành Digimon hệ Bóng Tối.' },
    { name: 'Gennai', role: 'Người hướng dẫn', description: 'Thực thể bí ẩn hỗ trợ những Đứa Trẻ Được Chọn.' },
    { name: 'Devimon', role: 'Kẻ phản diện', description: 'Digimon ác quỷ, kẻ thù lớn đầu tiên của nhóm Taichi.' },
    { name: 'Vamdemon', role: 'Kẻ phản diện', description: 'Digimon ma cà rồng, âm mưu xâm chiếm thế giới thực.' },
    { name: 'Piedmon', role: 'Kẻ phản diện', description: 'Thủ lĩnh của Dark Masters, Digimon hề cực kỳ nguy hiểm.' }
  ]
};
