import { FanficWork } from '../types';

export const dragonBall: FanficWork = {
  id: 'dragon-ball',
  title: 'Dragon Ball Z',
  description: 'Goku và những chiến binh Z bảo vệ Trái Đất khỏi những kẻ thù hùng mạnh ngoài vũ trụ.',
  country: 'Nhật',
  plot: 'Goku, một chiến binh Saiyan được gửi đến Trái Đất khi còn nhỏ, lớn lên và trở thành người bảo vệ hành tinh. Cùng với những người bạn, anh đối đầu với các thế lực tà ác như Frieza, Cell và Majin Buu. Cuộc hành trình tìm kiếm 7 viên ngọc rồng có khả năng ban điều ước luôn là trung tâm của những cuộc phiêu lưu.',
  worldSetting: 'Vũ trụ rộng lớn với nhiều hành tinh và chủng tộc khác nhau. Sức mạnh được đo bằng Ki, cho phép bay lượn và thi triển các đòn đánh năng lượng. Các cấp độ biến hình Super Saiyan mang lại sức mạnh vượt trội.',
  characters: [
    { name: 'Son Goku', role: 'Nhân vật chính', age: '30', description: 'Chiến binh Saiyan thuần khiết, luôn khao khát sức mạnh và bảo vệ hòa bình thế giới. Sở hữu các cấp độ Super Saiyan và Bản năng vô cực.' },
    { name: 'Vegeta', role: 'Đối thủ / Đồng minh', age: '35', description: 'Hoàng tử Saiyan kiêu hãnh, ban đầu là kẻ thù nhưng sau đó trở thành đồng minh quan trọng nhất của Goku, luôn nỗ lực để vượt qua anh.' },
    { name: 'Gohan', role: 'Anh hùng', age: '18', description: 'Con trai của Goku, sở hữu tiềm năng sức mạnh khổng lồ nhưng lại yêu thích học thuật hơn là chiến đấu. Anh có hình thái Beast cực mạnh.' },
    { name: 'Piccolo', role: 'Người dẫn dắt', age: '25', description: 'Người Namek, ban đầu là kẻ thù nhưng sau đó trở thành người thầy và người bạn đáng tin cậy nhất của Gohan và Goku.' },
    { name: 'Frieza', role: 'Phản diện chính', age: '100+', description: 'Hoàng đế vũ trụ tàn ác, kẻ đã hủy diệt hành tinh Saiyan. Hắn luôn quay lại với những hình thái mới mạnh mẽ hơn như Golden hay Black Frieza.' },
    { name: 'Bulma', role: 'Thiên tài công nghệ', age: '30', description: 'Người đã phát minh ra máy dò ngọc rồng và là bộ não hỗ trợ đắc lực cho các chiến binh Z. Vợ của Vegeta.' },
    { name: 'Trunks', role: 'Chiến binh tương lai', age: '17', description: 'Con trai của Vegeta và Bulma, đến từ tương lai để cảnh báo về các mối đe dọa và giúp đỡ các chiến binh Z bảo vệ dòng thời gian.' },
    { name: 'Beerus', role: 'Thần Hủy Diệt', age: 'Millions', description: 'Thần Hủy Diệt của Vũ trụ 7, sở hữu sức mạnh áp đảo và niềm đam mê mãnh liệt với ẩm thực Trái Đất.' },
    { name: 'Whis', role: 'Thiên sứ', age: 'Unknown', description: 'Người hầu và sư phụ của Beerus, một thiên sứ với sức mạnh và kiến thức vô hạn, người đang dạy Goku Bản năng vô cực.' },
    { name: 'Majin Buu', role: 'Đồng minh / Cựu phản diện', age: 'Ancient', description: 'Sinh vật ma thuật cổ xưa, sau khi được thanh tẩy đã trở thành một người bạn tốt bụng nhưng cực kỳ ham ăn.' },
    { name: 'Broly', role: 'Siêu Saiyan huyền thoại', age: '30', description: 'Chiến binh Saiyan với sức mạnh tiềm ẩn điên cuồng, đang học cách kiểm soát bản thân trên hành tinh Vampa.' },
    { name: 'Krillin', role: 'Đồng minh', age: '30', description: 'Bạn thân nhất của Goku từ nhỏ, người Trái Đất mạnh nhất, luôn dũng cảm chiến đấu dù biết mình yếu thế hơn.' },
    { name: 'Yamcha', role: 'Đồng minh', age: '32', description: 'Cựu cướp sa mạc, một chiến binh Z đời đầu với kỹ năng Lang Nha Phong Phong Quyền đặc trưng.' },
    { name: 'Tien Shinhan', role: 'Đồng minh', age: '33', description: 'Võ sư phái Hạc, sở hữu ba mắt và các kỹ năng mạnh mẽ như Tân Khí Công Pháo, luôn nghiêm túc trong luyện tập.' },
    { name: 'Master Roshi', role: 'Người dẫn dắt', age: '300+', description: 'Quy Lão Tiên Sinh, sư phụ đầu tiên của Goku và Krillin, người đã sáng tạo ra chiêu thức Kamehameha huyền thoại.' },
    { name: 'Chi-Chi', role: 'Gia đình', age: '30', description: 'Vợ của Goku, một người mẹ nghiêm khắc luôn muốn con cái học hành thành tài nhưng cũng rất yêu thương gia đình.' },
    { name: 'Videl', role: 'Đồng minh', age: '18', description: 'Con gái của Mr. Satan, vợ của Gohan, một nữ võ sĩ mạnh mẽ và chính trực.' },
    { name: 'Goten', role: 'Anh hùng trẻ', age: '7', description: 'Con trai thứ hai của Goku, sở hữu tiềm năng thiên bẩm và có thể biến thành Super Saiyan từ khi còn rất nhỏ.' },
    { name: 'Kid Trunks', role: 'Anh hùng trẻ', age: '8', description: 'Con trai của Vegeta ở dòng thời gian hiện tại, tính cách tinh nghịch và là bạn thân nhất của Goten.' },
    { name: 'Cell', role: 'Phản diện', age: 'N/A', description: 'Sinh vật nhân tạo hoàn hảo mang gen của các chiến binh mạnh nhất, kẻ đã tổ chức trò chơi Cell Game đe dọa Trái Đất.' },
    { name: 'Android 17', role: 'Đồng minh', age: '25', description: 'Người nhân tạo mạnh mẽ, sau này trở thành người bảo vệ thiên nhiên và là người hùng thầm lặng trong Giải đấu Sức mạnh.' },
    { name: 'Android 18', role: 'Đồng minh', age: '25', description: 'Chị gái của Android 17, vợ của Krillin, một nữ chiến binh lạnh lùng nhưng rất quan tâm đến gia đình.' },
    { name: 'Mr. Satan', role: 'Anh hùng (Tự phong)', age: '40', description: 'Võ sư nổi tiếng thế giới, người luôn nhận vơ công lao đánh bại các phản diện. Dù yếu nhưng ông có lòng dũng cảm kỳ lạ và là bạn thân của Majin Buu.' },
    { name: 'King Kai', role: 'Thần giới', age: 'Ancient', description: 'Thần phương Bắc, người đã dạy Goku chiêu thức Kaioken và Quả Cầu Khinh Khi. Ông có khiếu hài hước kỳ quặc và sống trên một hành tinh siêu nhỏ.' },
    { name: 'Shin (Supreme Kai)', role: 'Thần giới', age: 'Ancient', description: 'Đông Giới Vương Thần, người cai quản vũ trụ. Ông luôn lo lắng về các mối đe dọa và thường xuyên nhờ cậy các chiến binh Z.' },
    { name: 'Zamasu', role: 'Phản diện', age: 'Ancient', description: 'Một Kai tập sự với tư tưởng cực đoan, muốn tiêu diệt mọi sinh linh để tạo ra một thế giới hoàn hảo.' },
    { name: 'Goku Black', role: 'Phản diện', age: 'N/A', description: 'Zamasu trong thân xác của Goku từ một dòng thời gian khác. Hắn sở hữu sức mạnh Super Saiyan Rosé và sự tàn bạo vô biên.' },
    { name: 'Jiren', role: 'Đối thủ', age: 'Unknown', description: 'Chiến binh mạnh nhất Vũ trụ 11, người sở hữu sức mạnh vượt qua cả Thần Hủy Diệt. Anh là đối thủ lớn nhất của Goku trong Giải đấu Sức mạnh.' },
    { name: 'Hit', role: 'Sát thủ / Đồng minh', age: '1000+', description: 'Sát thủ huyền thoại của Vũ trụ 6 với khả năng ngưng đọng thời gian. Anh là một chiến binh danh dự và luôn tôn trọng đối thủ.' },
    { name: 'Toppo', role: 'Đối thủ', age: 'Unknown', description: 'Lãnh đạo của Biệt đội Kiêu hãnh Vũ trụ 11, ứng cử viên cho vị trí Thần Hủy Diệt. Anh chiến đấu vì công lý tuyệt đối.' },
    { name: 'Caulifla', role: 'Chiến binh Saiyan', age: '18', description: 'Nữ Saiyan từ Vũ trụ 6 với tiềm năng cực lớn. Cô có tính cách mạnh mẽ, hoang dã và luôn khao khát đạt được các cấp độ Super Saiyan mới.' },
    { name: 'Kale', role: 'Chiến binh Saiyan', age: '17', description: 'Em gái kết nghĩa của Caulifla, sở hữu sức mạnh Super Saiyan cuồng nộ giống như Broly. Cô rất nhút nhát nhưng sẽ bùng nổ khi bảo vệ chị mình.' },
    { name: 'Cabba', role: 'Chiến binh Saiyan', age: '17', description: 'Saiyan trẻ tuổi từ Vũ trụ 6, người coi Vegeta là sư phụ. Anh là một chiến binh chính trực và luôn nỗ lực bảo vệ hành tinh Sadala.' }
  ]
};
