import { FanficWork } from '../types';

export const girlfriends100: FanficWork = {
  id: '100Girlfriends',
  title: 'Kimi no koto ga Dai Dai Dai Dai Daisuki na 100-nin no Kanojo',
  description: 'Aijo Rentarou, một chàng trai bị từ chối 100 lần, phát hiện ra mình có 100 "tri kỷ" và phải khiến tất cả họ hạnh phúc nếu không họ sẽ chết.',
  country: 'Nhật',
  plot: 'Aijo Rentarou là một chàng trai cực kỳ chân thành nhưng lại bị từ chối tình cảm 100 lần trong suốt thời học sinh. Vào ngày tốt nghiệp cấp hai, cậu đến đền thờ cầu nguyện và được Thần Tình Yêu tiết lộ một sự thật gây sốc: do một sai sót trên thiên đình, cậu có tới 100 "tri kỷ" (soulmates). Tuy nhiên, có một cái giá cực kỳ đắt: nếu cậu không thể khiến tất cả 100 người họ hạnh phúc, những người không thành đôi với cậu sẽ gặp tai nạn và qua đời. Quyết tâm bảo vệ tất cả những người phụ nữ mình yêu, Rentarou bắt đầu hành trình xây dựng một đại gia đình harem hạnh phúc nhất thế gian.',
  worldSetting: 'Bối cảnh học đường Nhật Bản hiện đại nhưng mang đậm tính hài hước, siêu thực và phá vỡ bức tường thứ tư. Thế giới này vận hành dựa trên quy luật "tri kỷ" tuyệt đối, nơi tình yêu có thể vượt qua mọi rào cản về tính cách, tuổi tác và hoàn cảnh.',
  characters: [
    { name: 'Aijo Rentarou', role: 'Nhân vật chính', age: '16', description: 'Một chàng trai cực kỳ tốt bụng, chân thành và sẵn sàng hy sinh mọi thứ vì hạnh phúc của các bạn gái. Cậu sở hữu ý chí sắt đá và khả năng yêu thương vô hạn.' },
    { name: 'Hanazono Hakari', role: 'Bạn gái #1', age: '16', description: 'Một cô gái quyến rũ, hay mơ mộng và có phần "biến thái" nhẹ. Cô rất chủ động trong việc thể hiện tình cảm với Rentarou.' },
    { name: 'Inda Karane', role: 'Bạn gái #2', age: '16', description: 'Một cô nàng Tsundere điển hình với sức mạnh thể chất đáng kinh ngạc. Cô luôn miệng nói ghét nhưng hành động lại chứng minh điều ngược lại.' },
    { name: 'Yoshimoto Shizuka', role: 'Bạn gái #3', age: '16', description: 'Một cô bé nhút nhát, nhỏ nhắn và chỉ giao tiếp thông qua việc chỉ tay vào các dòng chữ trong cuốn sách yêu thích của mình.' },
    { name: 'Eiyuu Nano', role: 'Bạn gái #4', age: '16', description: 'Một thiên tài với tư duy cực kỳ logic và hiệu quả. Cô ban đầu coi tình yêu là lãng phí thời gian nhưng đã bị Rentarou thuyết phục.' },
    { name: 'Yakuzen Kusuri', role: 'Bạn gái #5', age: '18 (thân hình 8)', description: 'Một thiên tài hóa học luôn thử nghiệm các loại thuốc kỳ lạ. Cô thường xuất hiện trong thân hình một đứa trẻ do tác dụng phụ của thuốc.' },
    { name: 'Hanazono Hahari', role: 'Bạn gái #6', age: '29', description: 'Mẹ của Hakari, một người phụ nữ giàu có và cũng là tri kỷ của Rentarou. Cô có tính cách khá giống con gái mình nhưng ở mức độ "cuồng nhiệt" hơn.' },
    { name: 'Haraga Kurumi', role: 'Bạn gái #7', age: '15', description: 'Một cô gái luôn cảm thấy đói bụng. Tâm trạng của cô thay đổi thất thường tùy thuộc vào việc cô đã được ăn hay chưa.' },
    { name: 'Meido Mei', role: 'Bạn gái #8', age: '19', description: 'Hầu gái trung thành của gia đình Hanazono. Cô có đôi mắt cầu vồng tuyệt đẹp nhưng thường nhắm lại để thể hiện sự phục tùng.' },
    { name: 'Sutou Iku', role: 'Bạn gái #9', age: '16', description: 'Thành viên câu lạc bộ bóng chày với sở thích "khổ hạnh". Cô tìm thấy niềm vui trong việc rèn luyện thể chất cực khổ.' },
    { name: 'Utsushimi Mimimi', role: 'Bạn gái #10', age: '17', description: 'Một cô gái cực kỳ quan tâm đến vẻ đẹp bản thân và sự thanh lịch. Cô luôn nỗ lực để trở nên xinh đẹp nhất có thể.' },
    { name: 'Kakure Meme', role: 'Bạn gái #11', age: '16', description: 'Một cô gái có vòng một lớn nhưng cực kỳ nhút nhát, luôn tìm cách che giấu khuôn mặt mình bằng tóc mái hoặc các vật dụng khác.' },
    { name: 'Ichiuchi Chiyo', role: 'Bạn gái #12', age: '13', description: 'Em họ của Rentarou, một cô bé nghiêm túc, đeo kính và luôn muốn mọi thứ phải thật ngăn nắp, đúng quy trình.' },
    { name: 'Naddy (Yamato Nadeshiko)', role: 'Bạn gái #13', age: '24', description: 'Giáo viên tiếng Anh nhưng lại cực kỳ cuồng văn hóa Mỹ (dù hiểu sai khá nhiều). Cô luôn ăn mặc và hành động như một người Mỹ.' },
    { name: 'Yasashiki Yamame', role: 'Bạn gái #14', age: '17', description: 'Một cô gái khổng lồ với tâm hồn nhân hậu, yêu quý thiên nhiên và động vật đến mức không nỡ làm hại cả sâu bọ.' },
    { name: 'Momi Momiji', role: 'Bạn gái #15', age: '16', description: 'Một chuyên gia massage với đôi bàn tay "ma thuật". Cô có khả năng đọc vị cảm xúc của người khác thông qua việc chạm vào cơ thể họ.' },
    { name: 'Yakuzen Yaku', role: 'Bạn gái #16', age: '89 (thân hình 8)', description: 'Bà của Kusuri, một người phụ nữ am hiểu về các loại thuốc truyền thống và có phong thái của một người lớn tuổi trong thân hình trẻ thơ.' },
    { name: 'Torotoro Kishika', role: 'Bạn gái #17', age: '18', description: 'Đội trưởng câu lạc bộ Kendo mạnh mẽ, nhưng lại có một bí mật là thích được nuông chiều như một đứa trẻ.' },
    { name: 'Kuraishi Mai', role: 'Bạn gái #18', age: '16', description: 'Hầu gái tập sự, người cực kỳ ngưỡng mộ Mei và ban đầu coi Rentarou là đối thủ cạnh tranh sự chú ý của Mei.' },
    { name: 'Ahko (Kumi Ashida)', role: 'Bạn gái #19', age: '16', description: 'Một cô nàng Gyaru với phong cách thời trang rực rỡ nhưng lại có nhịp tim cực kỳ thấp, khiến cô luôn trông có vẻ lờ đờ.' },
    { name: 'Uto Utami', role: 'Bạn gái #20', age: '15', description: 'Một cô gái thích đóng vai thi sĩ lang thang, thường xuyên nói những câu triết lý khó hiểu và thổi sáo ocarina.' },
    { name: 'Mairo Momoha', role: 'Bạn gái #21', age: '27', description: 'Nữ tu sĩ của đền thờ nhưng lại có những thói quen xấu như uống rượu và cờ bạc. Cô luôn đấu tranh giữa bản chất con người và trách nhiệm tôn giáo.' },
    { name: 'Baio Rin', role: 'Bạn gái #22', age: '15', description: 'Một cô gái yêu thích âm nhạc cổ điển nhưng lại có niềm đam mê kỳ lạ với những thứ kinh dị và bạo lực trong nghệ thuật.' },
    { name: 'Hifumi Suu', role: 'Bạn gái #23', age: '16', description: 'Một cô gái cực kỳ yêu thích các con số, đến mức cô coi chúng như những thực thể có cảm xúc.' },
    { name: 'Kaho Eira', role: 'Bạn gái #24', age: '20', description: 'Một cô gái lai Brazil với kỹ năng Capoeira điêu luyện. Cô sợ tất cả những thứ cô không thể đá được (như ma quỷ).' },
    { name: 'Nekonari Tama', role: 'Bạn gái #25', age: '21', description: 'Một cựu nhân viên văn phòng đã từ bỏ xã hội để sống như một con mèo. Cô được Rentarou nhận nuôi và yêu thương.' },
    { name: 'Saiki Himeka', role: 'Bạn gái #26', age: '16', description: 'Một thần tượng âm nhạc nổi tiếng nhưng lại luôn khao khát được trở nên "kỳ quặc" và khác biệt.' },
    { name: 'Dei Matsuri', role: 'Bạn gái #27', age: '15', description: 'Một cô gái yêu thích các lễ hội truyền thống và có phong cách nói chuyện như một nghệ nhân lâu năm.' },
    { name: 'Thần Tình Yêu', role: 'Thần linh', age: 'Unknown', description: 'Vị thần đã gây ra sai sót khiến Rentarou có 100 tri kỷ. Ông thường xuyên xuất hiện để hỗ trợ hoặc giải thích các quy luật tình yêu.' },
    { name: 'Baba An', role: 'Hiệu trưởng', age: '60s', description: 'Vị hiệu trưởng nghiêm khắc của trường Rentarou, người luôn giám sát các hoạt động của học sinh.' },
    { name: 'Asakawa', role: 'Bạn học', age: '16', description: 'Cô gái đầu tiên từ chối Rentarou ở cấp ba, khởi đầu cho chuỗi sự kiện của bộ truyện.' },
    { name: 'Friend A', role: 'Bạn thân', age: '16', description: 'Người bạn thân nhất của Rentarou, luôn ủng hộ và lắng nghe những tâm sự của cậu.' },
    { name: 'Yakuzen Kusuo', role: 'Cha Kusuri', age: '40s', description: 'Cha của Kusuri, cũng là một nhà nghiên cứu hóa học tài năng.' },
    { name: 'Yakuzen Kasue', role: 'Mẹ Kusuri', age: '40s', description: 'Mẹ của Kusuri, người luôn ủng hộ những thí nghiệm điên rồ của con gái.' },
    { name: 'Hanazono Teruo', role: 'Cha Hakari (đã mất)', age: 'N/A', description: 'Người chồng quá cố của Hahari, người đã để lại di nguyện mong muốn vợ mình tìm được hạnh phúc mới.' },
    { name: 'Chiyo\'s Father', role: 'Cha Chiyo', age: '40s', description: 'Chú của Rentarou, một người đàn ông nghiêm túc và yêu thương con gái hết mực.' },
    { name: 'Uncle Hiro', role: 'Chú Rentarou', age: '40s', description: 'Người chú vui tính thường xuyên xuất hiện trong các buổi họp mặt gia đình.' },
    { name: 'Aijo\'s Mother', role: 'Mẹ Rentarou', age: '40s', description: 'Người mẹ hiền hậu luôn lo lắng cho con trai mình.' },
    { name: 'Aijo\'s Father', role: 'Cha Rentarou', age: '40s', description: 'Người cha mẫu mực đã truyền dạy cho Rentarou những giá trị về sự chân thành.' },
    { name: 'God of Love\'s Assistant', role: 'Thần linh', age: 'Unknown', description: 'Trợ lý của Thần Tình Yêu, người giúp ông quản lý các hồ sơ tri kỷ.' }
  ]
};
