import { FanficWork } from '../types';

export const greatestEstateDeveloper: FanficWork = {
  id: 'greatestEstateDeveloper',
  title: 'Bậc Thầy Thiết Kế Điền Trang',
  description: 'Lloyd Frontera, một kỹ sư xây dựng xuyên không vào thân xác một thiếu gia ăn chơi trác táng, sử dụng kiến thức kỹ thuật để cứu lấy gia tộc và xây dựng đế chế.',
  country: 'Hàn',
  plot: 'Kim Suho, một kỹ sư xây dựng dân dụng, xuyên không vào cuốn tiểu thuyết yêu thích của mình dưới thân xác Lloyd Frontera - một thiếu gia ăn chơi, nợ nần chồng chất của một gia đình quý tộc đang lụi bại. Thay vì chấp nhận số phận, Lloyd sử dụng kiến thức chuyên môn về xây dựng, kiến trúc và kỹ thuật dân dụng để cứu vãn tình hình tài chính của gia đình, xây dựng các công trình vĩ đại và đối phó với những thế lực thù địch bằng sự thông minh (và đôi khi là sự gian xảo) của mình.',
  worldSetting: 'Một thế giới giả tưởng mang phong cách Trung Cổ với ma thuật, quái vật và các hệ thống quý tộc. Điểm độc đáo là sự kết hợp giữa kỹ thuật xây dựng hiện đại và các yếu tố kỳ ảo như triệu hồi quái vật để hỗ trợ thi công.',
  characters: [
    { name: 'Lloyd Frontera', role: 'Nhân vật chính', age: '20s', description: 'Kỹ sư xây dựng xuyên không. Anh nổi tiếng với khuôn mặt "gian xảo", tính cách thực dụng nhưng cực kỳ tài giỏi trong việc thiết kế và thi công công trình.' },
    { name: 'Javier Asrahan', role: 'Hộ vệ / Hiệp sĩ', age: '20s', description: 'Nhân vật chính của cuốn tiểu thuyết gốc. Một thiên tài kiếm thuật lạnh lùng, người ban đầu rất ghét Lloyd nhưng dần trở thành cộng sự trung thành nhất.' },
    { name: 'Alicia Magrath', role: 'Nữ hoàng', age: '20s', description: 'Nữ hoàng của vương quốc Cremo, một nhà lãnh đạo mạnh mẽ và quyết đoán, người đánh giá cao tài năng của Lloyd.' },
    { name: 'Arcos Frontera', role: 'Nam tước', age: '50s', description: 'Cha của Lloyd, một người đàn ông hiền lành nhưng từng bất lực trước cảnh gia đình nợ nần.' },
    { name: 'Bayal Frontera', role: 'Nam tước phu nhân', age: '40s', description: 'Mẹ của Lloyd, người luôn yêu thương và tin tưởng con trai mình bất kể điều gì.' },
    { name: 'Julian Frontera', role: 'Em trai', age: '10s', description: 'Em trai của Lloyd, một cậu bé thông minh và luôn ngưỡng mộ anh trai mình.' },
    { name: 'Xandra', role: 'Quái vật triệu hồi', age: 'Unknown', description: 'Một con quái vật đất mạnh mẽ được Lloyd triệu hồi để hỗ trợ các công trình xây dựng nặng nhọc.' },
    { name: 'Ppodong', role: 'Quái vật triệu hồi', age: 'Unknown', description: 'Một con rồng nhỏ đáng yêu có khả năng phun lửa, giúp Lloyd trong việc nung gạch và luyện kim.' },
    { name: 'Hamangi', role: 'Quái vật triệu hồi', age: 'Unknown', description: 'Quái vật có khả năng xử lý nước và bùn, cực kỳ hữu ích trong các công trình thủy lợi.' },
    { name: 'Kkingkking', role: 'Quái vật triệu hồi', age: 'Unknown', description: 'Quái vật có khả năng nén đất và tạo nền móng vững chắc.' },
    { name: 'Bailon', role: 'Quản gia', age: '60s', description: 'Quản gia trung thành của gia đình Frontera, người đã chứng kiến sự thay đổi ngoạn mục của Lloyd.' },
    { name: 'Neumann', role: 'Phản diện', age: '30s', description: 'Một kẻ mưu mô luôn tìm cách hãm hại gia đình Frontera và chiếm đoạt tài sản của họ.' },
    { name: 'Lacus', role: 'Hiệp sĩ', age: '20s', description: 'Một hiệp sĩ dưới trướng Nữ hoàng Alicia, ban đầu nghi ngờ Lloyd nhưng sau đó bị thuyết phục bởi tài năng của anh.' },
    { name: 'Serazade', role: 'Công chúa', age: '20s', description: 'Công chúa của một vương quốc lân bang, người có mối quan hệ ngoại giao phức tạp với Lloyd.' },
    { name: 'Cannavaro', role: 'Thợ rèn', age: '40s', description: 'Bậc thầy thợ rèn giúp Lloyd chế tạo các công cụ xây dựng đặc biệt.' },
    { name: 'Groggy', role: 'Công nhân', age: '30s', description: 'Một trong những công nhân xây dựng đầu tiên tin tưởng và làm việc dưới trướng Lloyd.' },
    { name: 'Hestia', role: 'Pháp sư', age: '20s', description: 'Pháp sư hỗ trợ Lloyd trong việc kết hợp ma thuật vào các công trình kiến trúc.' },
    { name: 'Zod', role: 'Thương nhân', age: '50s', description: 'Một thương nhân giàu có và nhạy bén, đối tác kinh doanh chiến lược của Lloyd.' },
    { name: 'Mikhail', role: 'Hiệp sĩ', age: '30s', description: 'Đối thủ của Javier trong giới hiệp sĩ, người luôn tìm cách thách thức sức mạnh của anh.' },
    { name: 'Elena', role: 'Thánh nữ', age: '20s', description: 'Thánh nữ của giáo hội, người có khả năng chữa trị và thanh tẩy, đôi khi hỗ trợ Lloyd trong các tình huống nguy cấp.' },
    { name: 'Bruno', role: 'Kiến trúc sư', age: '40s', description: 'Một kiến trúc sư truyền thống ban đầu phản đối các phương pháp của Lloyd nhưng sau đó trở thành học trò của anh.' },
    { name: 'Celia', role: 'Nữ hầu', age: '20s', description: 'Nữ hầu thân cận của gia đình Frontera, người chăm sóc sinh hoạt hàng ngày cho Lloyd.' },
    { name: 'Dante', role: 'Lãnh chúa', age: '40s', description: 'Một lãnh chúa tham lam luôn tìm cách thu thuế nặng nề, đối thủ chính trị của Lloyd.' },
    { name: 'Fabio', role: 'Đầu bếp', age: '40s', description: 'Đầu bếp của gia đình Frontera, người luôn đau đầu với những yêu cầu ẩm thực kỳ lạ của Lloyd.' },
    { name: 'Galahad', role: 'Hiệp sĩ thánh', age: '30s', description: 'Một hiệp sĩ chính trực luôn bảo vệ công lý, đôi khi xung đột với tính cách thực dụng của Lloyd.' },
    { name: 'Isabella', role: 'Nữ bá tước', age: '30s', description: 'Một người phụ nữ quyền lực trong giới thượng lưu, người giúp Lloyd mở rộng các mối quan hệ xã hội.' },
    { name: 'Kael', role: 'Sát thủ', age: '20s', description: 'Một sát thủ được thuê để ám sát Lloyd nhưng sau đó bị anh "thu phục" bằng lợi ích kinh tế.' },
    { name: 'Luna', role: 'Tinh linh', age: 'Unknown', description: 'Tinh linh rừng hỗ trợ Lloyd trong việc bảo vệ môi trường xung quanh các công trình xây dựng.' },
    { name: 'Marcus', role: 'Thợ mỏ', age: '40s', description: 'Trưởng nhóm thợ mỏ giúp Lloyd khai thác tài nguyên đá và kim loại.' },
    { name: 'Nina', role: 'Thương nhân trẻ', age: '20s', description: 'Con gái của Zod, một cô gái thông minh và có khiếu kinh doanh giống cha.' },
    { name: 'Oliver', role: 'Lâm tặc (đã hoàn lương)', age: '30s', description: 'Từng là kẻ phá hoại rừng nhưng sau đó làm việc cho Lloyd trong việc quản lý gỗ xây dựng.' },
    { name: 'Petra', role: 'Nữ pháp sư bóng tối', age: '30s', description: 'Một nhân vật bí ẩn ban đầu là kẻ thù nhưng sau đó có những thỏa thuận ngầm với Lloyd.' },
    { name: 'Quentin', role: 'Sử gia', age: '60s', description: 'Người ghi chép lại những công trạng vĩ đại của Lloyd cho hậu thế.' },
    { name: 'Roderick', role: 'Đại công tước', age: '50s', description: 'Một trong những người quyền lực nhất vương quốc, người có cái nhìn khắt khe với Lloyd.' },
    { name: 'Silvia', role: 'Cung thủ', age: '20s', description: 'Một cung thủ tài ba hỗ trợ Javier trong việc bảo vệ các công trường xây dựng.' },
    { name: 'Tristan', role: 'Hiệp sĩ trẻ', age: '10s', description: 'Học trò của Javier, người luôn cố gắng rèn luyện để mạnh mẽ như thầy mình.' },
    { name: 'Ursula', role: 'Bà đồng', age: '70s', description: 'Người đưa ra những lời tiên tri kỳ lạ về tương lai của Lloyd.' },
    { name: 'Victor', role: 'Nhà phát minh', age: '40s', description: 'Người giúp Lloyd hiện thực hóa các bản vẽ kỹ thuật phức tạp thành máy móc thực tế.' },
    { name: 'Wanda', role: 'Chủ quán trọ', age: '40s', description: 'Người cung cấp thông tin tình báo cho Lloyd từ những lời đồn thổi của khách trọ.' },
    { name: 'Yuri', role: 'Kiếm sĩ tự do', age: '20s', description: 'Một kiếm sĩ lang thang đôi khi làm việc thuê cho Lloyd.' }
  ]
};
