
import { FanficWork } from '../types';

export const gundam: FanficWork = {
  id: 'gundam',
  title: 'Gundam (Vũ Trụ Mobile Suit)',
  description: 'Thế giới nơi con người sống trong các thuộc địa không gian, chiến đấu bằng những cỗ máy khổng lồ gọi là Mobile Suit. Amuro Ray vô tình lái Gundam, bắt đầu cuộc chiến giữa Liên Bang Trái Đất và Công Quốc Zeon.',
  country: 'Nhật',
  characters: [
    { name: 'Amuro Ray', role: 'Main Character (Newtype)', description: 'Phi công lái RX-78-2 Gundam, thiên tài Newtype với khả năng phản xạ và cảm nhận siêu việt.' },
    { name: 'Char Aznable', role: 'Đối thủ (Red Comet)', description: 'Phi công huyền thoại của Zeon, kẻ thù truyền kiếp và cũng là đối trọng của Amuro.' },
    { name: 'Sayla Mass', role: 'Thành viên White Base', description: 'Em gái của Char, phi công hỗ trợ và là người có tầm ảnh hưởng lớn đến Amuro.' },
    { name: 'Bright Noa', role: 'Thuyền trưởng White Base', description: 'Người lãnh đạo trẻ tuổi, nghiêm khắc và đầy trách nhiệm.' },
    { name: 'Fraw Bow', role: 'Bạn thân Amuro', description: 'Cô gái hiền lành, luôn chăm sóc và lo lắng cho Amuro.' },
    { name: 'Kai Shiden', role: 'Phi công Guncannon', description: 'Tính cách có phần mỉa mai nhưng là một phi công đáng tin cậy.' },
    { name: 'Hayato Kobayashi', role: 'Phi công Guntank', description: 'Người luôn nỗ lực hết mình để bắt kịp Amuro.' },
    { name: 'Ryu Jose', role: 'Phi công kỳ cựu', description: 'Người cố vấn và là tấm gương hy sinh cho các phi công trẻ.' },
    { name: 'Sleggar Law', role: 'Phi công hỗ trợ', description: 'Người có phong cách lãng tử và tinh thần chiến đấu cao.' },
    { name: 'Matilda Ajan', role: 'Sĩ quan tiếp vận', description: 'Người mà Amuro thầm ngưỡng mộ, biểu tượng của sự hy sinh.' },
    { name: 'Lalah Sune', role: 'Newtype của Zeon', description: 'Cô gái có tâm hồn đồng điệu với Amuro nhưng lại thuộc phe đối địch.' },
    { name: 'Dozle Zabi', role: 'Tướng quân Zeon', description: 'Người chỉ huy mạnh mẽ, yêu thương gia đình nhưng cực kỳ tàn bạo trên chiến trường.' },
    { name: 'Gihren Zabi', role: 'Lãnh đạo Zeon', description: 'Kẻ độc tài đầy tham vọng, muốn thống trị toàn bộ nhân loại.' },
    { name: 'Kycilia Zabi', role: 'Chỉ huy Zeon', description: 'Người phụ nữ mưu mô, nắm giữ lực lượng tình báo và đặc nhiệm.' },
    { name: 'Degwin Sodo Zabi', role: 'Quốc vương Zeon', description: 'Người đứng đầu gia tộc Zabi, mệt mỏi vì chiến tranh.' },
    { name: 'Ramba Ral', role: 'Phi công Zeon', description: 'Một chiến binh thực thụ, người đã dạy cho Amuro nhiều bài học về danh dự.' },
    { name: 'Crowley Hamon', role: 'Người tình của Ramba Ral', description: 'Người phụ nữ thông minh, trung thành và đầy bản lĩnh.' },
    { name: 'M\'Quve', role: 'Chỉ huy Zeon', description: 'Kẻ yêu thích nghệ thuật nhưng đầy mưu mô xảo quyệt.' },
    { name: 'Gadem', role: 'Phi công kỳ cựu Zeon', description: 'Người lái Zaku I, đại diện cho thế hệ phi công cũ.' },
    { name: 'Black Tri-Stars', role: 'Đội phi công Zeon', description: 'Bộ ba phi công nổi tiếng với chiến thuật Jet Stream Attack.' },
    { name: 'Kamille Bidan', role: 'Main Character (Zeta)', description: 'Newtype mạnh mẽ nhất, phi công lái Zeta Gundam.' },
    { name: 'Quattro Bajeena', role: 'Người dẫn dắt (Zeta)', description: 'Danh tính giả của Char Aznable khi gia nhập AEUG.' },
    { name: 'Emma Sheen', role: 'Phi công AEUG', description: 'Người phụ nữ chính trực, rời bỏ Titans để chiến đấu cho lẽ phải.' },
    { name: 'Reccoa Londe', role: 'Điệp viên AEUG', description: 'Người phụ nữ có tâm hồn phức tạp, cuối cùng phản bội để tìm kiếm sự công nhận.' },
    { name: 'Fa Yuiry', role: 'Bạn thân Kamille', description: 'Người luôn ở bên cạnh ủng hộ và chăm sóc Kamille.' },
    { name: 'Jerid Messa', role: 'Đối thủ của Kamille', description: 'Phi công Titans, kẻ thù không đội trời chung với Kamille.' },
    { name: 'Paptimus Scirocco', role: 'Kẻ phản diện (Zeta)', description: 'Thiên tài mưu mô, muốn thao túng lịch sử từ bóng tối.' },
    { name: 'Haman Karn', role: 'Lãnh đạo Neo Zeon', description: 'Người phụ nữ quyền lực, sở hữu khả năng Newtype cực mạnh.' },
    { name: 'Judau Ashta', role: 'Main Character (ZZ)', description: 'Phi công lái ZZ Gundam, tính cách lạc quan và mạnh mẽ.' },
    { name: 'Roux Louka', role: 'Phi công AEUG (ZZ)', description: 'Cô gái xinh đẹp, tài năng và là đồng đội của Judau.' },
    { name: 'Elpeo Ple', role: 'Newtype nhân tạo', description: 'Cô bé hồn nhiên nhưng mang trong mình sức mạnh hủy diệt.' },
    { name: 'Banagher Links', role: 'Main Character (Unicorn)', description: 'Phi công lái Unicorn Gundam, người tìm kiếm hy vọng cho nhân loại.' },
    { name: 'Audrey Burne (Mineva Zabi)', role: 'Nữ chính (Unicorn)', description: 'Công chúa của Zeon, người muốn chấm dứt vòng lặp chiến tranh.' },
    { name: 'Full Frontal', role: 'Kẻ phản diện (Unicorn)', description: 'Người được coi là "Char Aznable tái thế", mang tư tưởng hư vô.' },
    { name: 'Marida Cruz', role: 'Phi công Neo Zeon', description: 'Newtype nhân tạo với quá khứ đau thương, lái Kshatriya.' },
    { name: 'Riddhe Marcenas', role: 'Phi công Liên Bang', description: 'Người bị giằng xé giữa lý tưởng và trách nhiệm gia tộc.' },
    { name: 'Suberoa Zinnerman', role: 'Thuyền trưởng Garencieres', description: 'Người cha tinh thần của Marida, chiến binh Zeon kỳ cựu.' },
    { name: 'Daguza Mackle', role: 'Chỉ huy đặc nhiệm ECOAS', description: 'Người lính mẫu mực, hy sinh để bảo vệ Banagher.' },
    { name: 'Angelo Sauper', role: 'Phi công Neo Zeon', description: 'Người trung thành tuyệt đối với Full Frontal.' },
    { name: 'Haro', role: 'Robot hỗ trợ', description: 'Linh vật của dòng phim Gundam, người bạn đồng hành của nhiều phi công.' }
  ]
};
