import { FanficWork } from '../types';

export const kingdom: FanficWork = {
  id: 'kingdom',
  title: 'Kingdom',
  description: 'Hành trình của một thiếu niên nô lệ trở thành Đại Tướng Quân dưới trướng Tần Thủy Hoàng.',
  country: 'Nhật',
  plot: 'Lấy bối cảnh thời Chiến Quốc tại Trung Hoa, câu chuyện xoay quanh Tín, một thiếu niên nô lệ với ước mơ trở thành Thiên Hạ Đệ Nhất Đại Tướng Quân. Sau cái chết của người bạn thân Phiêu, Tín gặp gỡ Doanh Chính - vị vua trẻ của nước Tần. Cùng nhau, họ dấn thân vào những cuộc chiến khốc liệt để thống nhất Trung Hoa, chấm dứt kỷ nguyên chiến tranh kéo dài hàng thế kỷ.',
  worldSetting: 'Trung Hoa thời Chiến Quốc với 7 quốc gia hùng mạnh: Tần, Triệu, Ngụy, Sở, Yên, Hàn, Tề. Thế giới tập trung vào các chiến thuật quân sự quy mô lớn, sức mạnh của các vị tướng quân và những âm mưu chính trị thâm độc chốn cung đình.',
  characters: [
    { name: 'Tín (Li Xin)', role: 'Nhân vật chính', age: '20s', description: 'Thủ lĩnh Phi Tín Quân, một chiến binh dũng mãnh với ý chí sắt đá. Cậu đi lên từ thân phận nô lệ và quyết tâm trở thành Đại Tướng Quân.' },
    { name: 'Doanh Chính (Ying Zheng)', role: 'Tần Vương', age: '20s', description: 'Vị vua trẻ của nước Tần, người mang hoài bão thống nhất Trung Hoa để xóa bỏ chiến tranh vĩnh viễn.' },
    { name: 'Hà Liễu Điêu (He Liao Diao)', role: 'Quân sư', age: '20s', description: 'Hậu duệ của tộc Sơn Cước, quân sư tài ba của Phi Tín Quân và là người bạn thân thiết của Tín.' },
    { name: 'Khương Hội (Qiang Lei)', role: 'Phó tướng / Sát thủ', age: '20s', description: 'Thần đồng kiếm thuật của tộc Xi Vưu, sở hữu kỹ thuật "Vũ Điệu Thần Linh" cực kỳ lợi hại.' },
    { name: 'Vương Kỳ (Wang Qi)', role: 'Lục Đại Tướng Quân', age: '40s', description: 'Được mệnh danh là "Quái vật của nước Tần", một trong những vị tướng vĩ đại nhất lịch sử với uy thế áp đảo.' },
    { name: 'Đằng (Teng)', role: 'Đại Tướng Quân', age: '40s', description: 'Phó tướng trung thành của Vương Kỳ, một kiếm sĩ tài hoa với phong cách chiến đấu độc đáo và hài hước.' },
    { name: 'Vương Bí (Wang Ben)', role: 'Thủ lĩnh Ngọc Phụng Quân', age: '20s', description: 'Thiếu gia nhà Vương, một bậc thầy thương thuật với tính cách nghiêm túc và kiêu hãnh.' },
    { name: 'Mông Điềm (Meng Tian)', role: 'Thủ lĩnh Nhạc Hoa Quân', age: '20s', description: 'Thiên tài quân sự với khả năng ứng biến linh hoạt, tính cách phóng khoáng và thông minh.' },
    { name: 'Vương Tiễn (Wang Jian)', role: 'Đại Tướng Quân', age: '40s', description: 'Vị tướng bí ẩn với khả năng nhìn thấu mọi chiến cục, luôn đặt chiến thắng lên hàng đầu.' },
    { name: 'Mông Vũ (Meng Wu)', role: 'Đại Tướng Quân', age: '40s', description: 'Biểu tượng của sức mạnh cơ bắp nước Tần, người luôn tin rằng sức mạnh tuyệt đối có thể nghiền nát mọi chiến thuật.' },
    { name: 'Hoàn Kỵ (Huan Yi)', role: 'Đại Tướng Quân', age: '30s', description: 'Cựu thủ lĩnh băng cướp, một thiên tài chiến thuật tàn nhẫn và không thể lường trước.' },
    { name: 'Dương Đoan Hòa (Yang Duan He)', role: 'Sơn Vương', age: '20s', description: 'Nữ vương của các tộc Sơn Cước, một chiến binh dũng mãnh và là đồng minh quan trọng của Doanh Chính.' },
    { name: 'Lý Mục (Li Mu)', role: 'Thiên tài quân sự Triệu', age: '30s', description: 'Đệ nhất quân sư của nước Triệu, đối thủ lớn nhất của nước Tần trong công cuộc thống nhất.' },
    { name: 'Bàng Noãn (Pang Nuan)', role: 'Võ Thần', age: '40s', description: 'Một kẻ cuồng võ đạo, luôn tìm kiếm những đối thủ mạnh nhất để chứng minh mình là người mạnh nhất thế giới.' },
    { name: 'Lã Bất Vi (Lu Bu Wei)', role: 'Tướng quốc nước Tần', age: '50s', description: 'Một thương nhân giàu có vươn lên nắm quyền lực tuyệt đối, đối thủ chính trị lớn nhất của Doanh Chính.' },
    { name: 'Xương Văn Quân (Chang Wen Jun)', role: 'Đại thần', age: '50s', description: 'Người thầy và là người ủng hộ trung thành nhất của Doanh Chính từ những ngày đầu.' },
    { name: 'Xương Bình Quân (Chang Ping Jun)', role: 'Tổng tư lệnh', age: '30s', description: 'Thiên tài quân sự và chính trị, người vạch ra những kế hoạch chiến lược vĩ mô cho nước Tần.' },
    { name: 'Bích (Bi)', role: 'Tướng quân', age: '30s', description: 'Một vị tướng mẫu mực, trung thành và luôn nỗ lực hết mình để hỗ trợ Tín và Doanh Chính.' },
    { name: 'Bào Công (Duke Hyou)', role: 'Đại Tướng Quân', age: '60s', description: 'Vị tướng bản năng thuần túy, người coi chiến trường là một bữa tiệc rượu đầy phấn khích.' },
    { name: 'Liêm Pha (Lian Po)', role: 'Huyền thoại nước Triệu', age: '70s', description: 'Một trong những vị tướng vĩ đại nhất thời đại, sở hữu kinh nghiệm và uy thế khổng lồ.' },
    { name: 'Ngô Phượng Minh (Wu Feng Ming)', role: 'Thiên tài Ngụy', age: '20s', description: 'Bậc thầy về các loại máy móc chiến tranh và chiến thuật phòng thủ của nước Ngụy.' },
    { name: 'Oa Lân (Wa Lin)', role: 'Đại Tướng Quân Sở', age: '30s', description: 'Nữ tướng khổng lồ của nước Sở với trí tuệ đáng sợ và phong cách chỉ huy độc đoán.' },
    { name: 'Hạng Yên (Xiang Yan)', role: 'Đại Tướng Quân Sở', age: '50s', description: 'Vị tướng huyền thoại của nước Sở, người được coi là bức tường thành không thể phá vỡ.' },
    { name: 'Hàn Phi (Han Fei)', role: 'Nhà tư tưởng', age: '30s', description: 'Thiên tài pháp trị của nước Hàn, người có tầm ảnh hưởng sâu sắc đến tư tưởng của Doanh Chính.' },
    { name: 'Thái Trạch (Cai Ze)', role: 'Ngoại giao gia', age: '70s', description: 'Vị quan ngoại giao lão luyện, người đã phục vụ qua nhiều đời vua Tần.' },
    { name: 'Triệu Cao (Zhao Gao)', role: 'Hoạn quan', age: '30s', description: 'Kẻ đầy mưu mô chốn cung đình, luôn tìm cách thao túng quyền lực từ bóng tối.' },
    { name: 'Thành Kiều (Cheng Jiao)', role: 'Em trai Doanh Chính', age: '10s', description: 'Từng là kẻ phản loạn nhưng sau đó đã thay đổi và hy sinh để bảo vệ vương quyền của anh trai.' },
    { name: 'Thái Hậu (Tai Hou)', role: 'Mẹ Doanh Chính', age: '40s', description: 'Người phụ nữ quyền lực với quá khứ đau thương, luôn tìm cách xây dựng thế lực riêng trong cung.' },
    { name: 'Lao Ái (Lao Ai)', role: 'Người tình Thái Hậu', age: '30s', description: 'Kẻ được Lã Bất Vi cài vào để thao túng Thái Hậu, dẫn đến cuộc nổi loạn tại Ung Thành.' },
    { name: 'Lý Tư (Li Si)', role: 'Đại thần', age: '40s', description: 'Bậc thầy về luật pháp, người giúp Doanh Chính xây dựng hệ thống quản lý quốc gia sau khi thống nhất.' },
    { name: 'Mông Nghị (Meng Yi)', role: 'Quân sư tập sự', age: '10s', description: 'Em trai Mông Điềm, một quân sư trẻ đầy triển vọng đang học tập dưới trướng Xương Bình Quân.' },
    { name: 'Vương Hột (Wang He)', role: 'Lục Đại Tướng Quân cũ', age: 'Unknown', description: 'Một trong sáu vị tướng huyền thoại đời trước, nổi tiếng với sức mạnh và sự dũng mãnh.' },
    { name: 'Bạch Khởi (Bai Qi)', role: 'Lục Đại Tướng Quân cũ', age: 'Unknown', description: 'Vị tướng đáng sợ nhất lịch sử với biệt danh "Nhân Đồ", người đã chôn sống 40 vạn quân Triệu.' },
    { name: 'Tư Mã Thác (Sima Cuo)', role: 'Lục Đại Tướng Quân cũ', age: 'Unknown', description: 'Vị tướng tài ba với khả năng chinh phục các vùng đất hiểm trở.' },
    { name: 'Hồ Thương (Hu Shang)', role: 'Lục Đại Tướng Quân cũ', age: 'Unknown', description: 'Quân sư duy nhất trong bộ sáu huyền thoại, người vạch ra những chiến lược vĩ mô cho nước Tần.' },
    { name: 'Khương Liêu (Kyou)', role: 'Lục Đại Tướng Quân cũ', age: '20s (khi hy sinh)', description: 'Nữ tướng tài hoa, người đã chinh phục 99 thành trì và có mối tình sâu đậm với Vương Kỳ.' },
    { name: 'Mông Ngao (Mou Gou)', role: 'Đại Tướng Quân', age: '70s', description: 'Vị tướng hiền từ, người có khả năng nhìn người xuất sắc và là cha của Mông Vũ.' },
    { name: 'Triệu Trang (Chousou)', role: 'Tướng quân Triệu', age: '40s', description: 'Vị tướng chỉ huy quân Triệu trong chiến dịch Mã Dương, một chiến thuật gia cẩn trọng.' },
    { name: 'Phó Đề (Fu Di)', role: 'Tướng trẻ Triệu', age: '20s', description: 'Kiếm sĩ tốc độ của nước Triệu, người luôn coi Tín là đối thủ truyền kiếp.' },
    { name: 'Hải Niết (Kaine)', role: 'Nữ tướng Triệu', age: '20s', description: 'Cận vệ trung thành của Lý Mục, một nữ chiến binh dũng cảm và sắc sảo.' },
    { name: 'Ba Diêu (Ba Jio)', role: 'Chiến binh Sơn Cước', age: '20s', description: 'Chiến binh mạnh nhất dưới trướng Dương Đoan Hòa, một con quái vật thực sự trên chiến trường.' },
    { name: 'Tháp Từ Phu (Tajifu)', role: 'Chiến binh Sơn Cước', age: '20s', description: 'Chiến binh khổng lồ với sức mạnh kinh người, luôn đi đầu trong các cuộc tấn công của tộc Sơn Cước.' }
  ]
};
