
import { FanficWork } from '../types';

export const kyNguyenKyLa: FanficWork = {
  id: 'ky_nguyen_ky_la',
  title: 'Kỷ Nguyên Kỳ Lạ',
  description: 'Thế giới nơi các quy tắc vật lý bị bẻ cong, những hiện tượng kỳ quái xuất hiện khắp nơi. Lục Chu vô tình sở hữu khả năng nhìn thấy các "quy tắc" ẩn sau mọi sự vật, bắt đầu hành trình sinh tồn và khám phá bí mật của kỷ nguyên mới.',
  country: 'Trung',
  characters: [
    { name: 'Lục Chu', role: 'Main Character', description: 'Người sở hữu khả năng nhìn thấu các quy tắc kỳ lạ. Tính cách lạnh lùng, lý trí và cực kỳ nhạy bén.' },
    { name: 'Tiểu Vũ', role: 'Em gái Lục Chu', description: 'Cô bé có khả năng cảm nhận được sự nguy hiểm từ các hiện tượng kỳ lạ.' },
    { name: 'Lão Trương', role: 'Nhà nghiên cứu quy tắc', description: 'Người giúp Lục Chu hiểu rõ hơn về thế giới mới, có kiến thức uyên bác.' },
    { name: 'Trần Tuyết', role: 'Nữ đặc vụ', description: 'Thành viên của tổ chức quản lý các hiện tượng kỳ lạ, ban đầu giám sát Lục Chu.' },
    { name: 'Lâm Phong', role: 'Chiến binh quy tắc', description: 'Người có khả năng sử dụng các vật phẩm kỳ lạ để chiến đấu.' },
    { name: 'Vương Đại Lực', role: 'Người sống sót', description: 'Người có bản năng sinh tồn cực cao, đồng đội của Lục Chu.' },
    { name: 'Diệp Linh', role: 'Cô gái bí ẩn', description: 'Sở hữu khả năng điều khiển các quy tắc không gian.' },
    { name: 'Hắc Y Nhân', role: 'Kẻ thù bí ẩn', description: 'Thành viên của tổ chức muốn lợi dụng các quy tắc kỳ lạ để thống trị.' },
    { name: 'Lý Thanh', role: 'Nhà khoa học điên', description: 'Người thực hiện các thí nghiệm nguy hiểm trên con người và quy tắc.' },
    { name: 'Triệu Linh', role: 'Nữ bác sĩ', description: 'Chuyên gia chữa trị các vết thương do quy tắc gây ra.' },
    { name: 'Mục Thiết', role: 'Đối thủ của Lục Chu', description: 'Người có khả năng nhìn thấy quy tắc nhưng theo hướng tiêu cực.' },
    { name: 'Tần gia chủ', role: 'Thế lực ngầm', description: 'Người nắm giữ nhiều vật phẩm kỳ lạ quý hiếm.' },
    { name: 'Hàn Sương', role: 'Nữ chiến binh lạnh lùng', description: 'Tốc độ và sự chính xác là vũ khí của cô.' },
    { name: 'Lục Hải', role: 'Cha Lục Chu', description: 'Nhà nghiên cứu mất tích, để lại nhiều manh mối về kỷ nguyên kỳ lạ.' },
    { name: 'Vương Hổ', role: 'Người bảo vệ', description: 'Sức mạnh cơ bắp kết hợp với quy tắc phòng ngự.' },
    { name: 'Chu Hải', role: 'Nhà thám hiểm vùng cấm', description: 'Người thường xuyên đi vào các khu vực có quy tắc biến dị.' },
    { name: 'Mã Lực', role: 'Chiến binh hệ lôi', description: 'Sức mạnh tấn công bùng nổ từ quy tắc điện năng.' },
    { name: 'Hà Linh', role: 'Nữ y tá quy tắc', description: 'Người có khả năng làm dịu các hiện tượng kỳ lạ.' },
    { name: 'Tôn Kiên', role: 'Đội trưởng an ninh thành phố', description: 'Người có trách nhiệm cao, bảo vệ cư dân.' },
    { name: 'Lý Na', role: 'Phóng viên điều tra', description: 'Luôn theo sát các sự kiện kỳ lạ.' },
    { name: 'Trương Ba', role: 'Chiến binh hệ độc', description: 'Cách chiến đấu quỷ dị, sử dụng quy tắc ăn mòn.' },
    { name: 'Phạm Tiến', role: 'Nhà sưu tầm quy tắc', description: 'Người sở hữu bộ sưu tập vật phẩm kỳ lạ khổng lồ.' },
    { name: 'Đỗ Quyên', role: 'Nữ chiến binh hệ hoa', description: 'Vẻ đẹp đi kèm với sự nguy hiểm từ quy tắc thực vật.' },
    { name: 'Tạ Thiên', role: 'Thiên tài quy tắc phương Bắc', description: 'Đối thủ lớn nhất của Lục Chu.' },
    { name: 'Lục Bình', role: 'Chiến binh hệ thủy', description: 'Khả năng khống chế quy tắc chất lỏng.' },
    { name: 'Thần Quy Tắc Ý Chí', role: 'Thực thể cổ đại', description: 'Ý chí của thế giới mới, hướng dẫn Lục Chu.' },
    { name: 'Lục Chu (Tương lai)', role: 'Chúa Tể Quy Tắc', description: 'Hình ảnh Lục Chu khi đã làm chủ mọi quy tắc của vũ trụ.' },
    { name: 'Tiểu Hắc', role: 'Vật nuôi kỳ lạ', description: 'Con mèo đen có khả năng đi xuyên tường.' },
    { name: 'Bạch Lão', role: 'Người gác cổng', description: 'Người canh giữ lối vào các vùng cấm địa.' },
    { name: 'Thanh Nữ', role: 'Thực thể quy tắc', description: 'Cô gái được tạo ra từ các quy tắc thuần khiết.' },
    { name: 'Hồng Ma', role: 'Kẻ hủy diệt', description: 'Thực thể mang quy tắc hỗn loạn.' },
    { name: 'Lam Thần', role: 'Người bảo hộ', description: 'Thực thể mang quy tắc trật tự.' },
    { name: 'Tử Vương', role: 'Kẻ thống trị bóng tối', description: 'Thực thể mang quy tắc hư vô.' },
    { name: 'Kim Thánh', role: 'Người mang ánh sáng', description: 'Thực thể mang quy tắc sáng tạo.' },
    { name: 'Mộc Linh', role: 'Người mang sự sống', description: 'Thực thể mang quy tắc sinh trưởng.' },
    { name: 'Thổ Đế', role: 'Người mang sự ổn định', description: 'Thực thể mang quy tắc kiên cố.' },
    { name: 'Thủy Hậu', role: 'Người mang sự linh hoạt', description: 'Thực thể mang quy tắc biến hóa.' },
    { name: 'Hỏa Quân', role: 'Người mang sự hủy diệt', description: 'Thực thể mang quy tắc nhiệt năng.' },
    { name: 'Phong Tôn', role: 'Người mang sự tự do', description: 'Thực thể mang quy tắc tốc độ.' },
    { name: 'Lôi Đế', role: 'Người mang sự phán xét', description: 'Thực thể mang quy tắc uy áp.' }
  ]
};
