
import { FanficWork } from '../types';

export const maThuSieuThan: FanficWork = {
  id: 'ma_thu_sieu_than',
  title: 'Ma Thú Siêu Thần',
  description: 'Thế giới nơi con người có thể khế ước với ma thú. Tô Bình vô tình nhận được hệ thống nuôi dưỡng ma thú siêu thần, bắt đầu hành trình trở thành tiệm bán ma thú mạnh nhất vũ trụ.',
  country: 'Trung',
  characters: [
    { name: 'Tô Bình', role: 'Main Character', description: 'Chủ tiệm ma thú, sở hữu hệ thống siêu thần. Tính cách bao che khuyết điểm, thực lực thâm sâu khó lường.' },
    { name: 'Tô Lăng Nguyệt', role: 'Em gái Tô Bình', description: 'Thiên tài học viện, ban đầu coi thường anh trai nhưng sau đó vô cùng sùng bái.' },
    { name: 'Chung Linh Đồng', role: 'Đồ đệ Tô Bình', description: 'Cô gái có thiên phú nuôi dưỡng cực cao, được Tô Bình chỉ dạy.' },
    { name: 'Tang Thi Lão Long', role: 'Chiến sủng', description: 'Một trong những chiến sủng mạnh nhất của Tô Bình, có khả năng bất tử.' },
    { name: 'Luyện Ngục Chúc Long Thú', role: 'Chiến sủng', description: 'Chiến sủng chủ lực của Tô Bình, mang huyết thống rồng cực kỳ cao quý.' },
    { name: 'Nhị Cẩu (Hạo Thiên Khuyển)', role: 'Chiến sủng', description: 'Tính cách lầy lội nhưng trung thành, có khả năng phòng ngự và khống chế tuyệt vời.' },
    { name: 'Tiểu Hải (Hải Long Thú)', role: 'Chiến sủng', description: 'Chiến sủng hệ nước, cực kỳ thông minh và linh hoạt.' },
    { name: 'Ảnh Thú', role: 'Chiến sủng', description: 'Sát thủ trong bóng tối, tốc độ và khả năng ám sát kinh người.' },
    { name: 'Kiều An Na', role: 'Nhân viên tiệm (Thần tộc)', description: 'Nữ thần từ Thần giới, bị hệ thống thu phục làm nhân viên tiệm ma thú.' },
    { name: 'Đường Như Yên', role: 'Nhân viên tiệm (Đường gia)', description: 'Thiên kim tiểu thư Đường gia, ban đầu là con tin sau trở thành nhân viên tiệm.' },
    { name: 'Tạ Lam', role: 'Mẹ Tô Bình', description: 'Người phụ nữ hiền hậu, luôn lo lắng cho hai anh em Tô Bình.' },
    { name: 'Tô Viễn Sơn', role: 'Cha Tô Bình', description: 'Người đàn ông bí ẩn, có lai lịch không tầm thường.' },
    { name: 'Phí lão', role: 'Cao thủ bảo vệ Tô Lăng Nguyệt', description: 'Lão giả trung thành, có thực lực mạnh mẽ.' },
    { name: 'Lục Bằng Phi', role: 'Học viên học viện ma thú', description: 'Đối thủ ban đầu của Tô Lăng Nguyệt, sau bị thực lực của Tô Bình khuất phục.' },
    { name: 'Diệp Hạo', role: 'Thiên tài Long Giang', description: 'Người đứng đầu thế hệ trẻ Long Giang, rất tôn trọng Tô Bình.' },
    { name: 'Tần Đô Hoàng', role: 'Gia chủ Tần gia', description: 'Một trong những người ủng hộ Tô Bình sớm nhất tại Long Giang.' },
    { name: 'Chu Thiên Lâm', role: 'Gia chủ Chu gia', description: 'Ban đầu đối đầu với Tô Bình nhưng sau đó phải cúi đầu.' },
    { name: 'Ngô Quan Sinh', role: 'Bậc thầy nuôi dưỡng', description: 'Người có danh tiếng trong giới nuôi dưỡng, rất khâm phục kỹ thuật của Tô Bình.' },
    { name: 'Lâm Mạc Không', role: 'Đội trưởng đội khai hoang', description: 'Người thường xuyên dẫn đội vào các vùng nguy hiểm, là khách quen của tiệm.' },
    { name: 'Phàn Thượng Đức', role: 'Hiệu trưởng học viện Phượng Sơn', description: 'Người luôn tìm cách chiêu mộ Tô Bình về làm giảng viên.' },
    { name: 'Vân Vạn Lý', role: 'Truyền kỳ cường giả', description: 'Người bảo vệ Long Giang, có thực lực trấn áp một phương.' },
    { name: 'Lý Nguyên Phong', role: 'Truyền kỳ cường giả', description: 'Người trấn thủ thâm uyên, có ý chí kiên cường.' },
    { name: 'Bắc Hải Mục', role: 'Truyền kỳ cường giả', description: 'Người có danh tiếng lớn trong giới chiến sủng sư.' },
    { name: 'Tư Đồ Hồng', role: 'Truyền kỳ cường giả', description: 'Ban đầu có ý đồ xấu với Tô Bình nhưng bị trừng phạt.' },
    { name: 'Nhiếp Thành Không', role: 'Đội trưởng đội khai hoang', description: 'Người có kinh nghiệm phong phú, rất nể trọng Tô Bình.' },
    { name: 'Mạc Nh若', role: 'Thiên tài nuôi dưỡng', description: 'Cô gái xinh đẹp, luôn muốn thi đấu kỹ thuật với Tô Bình.' },
    { name: 'Cố Bắc Việt', role: 'Truyền kỳ cường giả', description: 'Người có tính cách hào sảng, là bạn tốt của Tô Bình.' },
    { name: 'Hàn Ngọc Tường', role: 'Giảng viên học viện', description: 'Người có kiến thức uyên bác về ma thú.' },
    { name: 'Tô Yến', role: 'Thành viên Tô gia', description: 'Người luôn tìm cách gây khó dễ cho gia đình Tô Bình.' },
    { name: 'Đường Lân', role: 'Thiên tài Đường gia', description: 'Anh trai Đường Như Yên, có thực lực cực mạnh.' },
    { name: 'Tần Thiếu Thiên', role: 'Thiên tài Tần gia', description: 'Người có ý chí chiến đấu cao, luôn muốn vượt qua Tô Bình.' },
    { name: 'Lưu Long', role: 'Thành viên đội khai hoang', description: 'Người có tính cách trầm ổn, đáng tin cậy.' },
    { name: 'Uông Nhạc', role: 'Đối thủ của Tô Bình', description: 'Kẻ luôn tìm cách hãm hại tiệm ma thú của Tô Bình.' },
    { name: 'Diệp Linh Đồng', role: 'Học viên nhỏ tuổi', description: 'Cô bé đáng yêu, rất thích các ma thú trong tiệm Tô Bình.' },
    { name: 'Tô Bình (Phân thân)', role: 'Thực thể hệ thống', description: 'Phân thân do hệ thống tạo ra để quản lý tiệm khi Tô Bình đi vắng.' },
    { name: 'Thần Linh Lão Giả', role: 'Thực thể Thần giới', description: 'Người hướng dẫn Tô Bình khi anh đến Thần giới tu luyện.' },
    { name: 'Hắc Long Vương', role: 'Yêu thú vương giả', description: 'Kẻ thống trị vùng đất hoang dã, đối thủ đáng gờm của Tô Bình.' },
    { name: 'Cửu Đầu Điểu', role: 'Ma thú cổ đại', description: 'Sinh vật huyền thoại với sức mạnh hủy diệt.' },
    { name: 'Tô Lăng Nguyệt (Tương lai)', role: 'Nữ đế', description: 'Hình ảnh tương lai của Tô Lăng Nguyệt khi đạt đến đỉnh cao thực lực.' },
    { name: 'Hệ Thống (Linh hồn)', role: 'Thực thể bí ẩn', description: 'Ý chí của hệ thống siêu thần, luôn thúc đẩy Tô Bình tiến lên.' }
  ]
};
