
import { FanficWork } from '../types';

export const thanSungTienHoa: FanficWork = {
  id: 'than_sung_tien_hoa',
  title: 'Thần Sủng Tiến Hóa',
  description: 'Thế giới sau thảm họa, động thực vật biến dị thành quái vật. Con người thức tỉnh khả năng ngự thú. Cao Bằng sở hữu khả năng nhìn thấy lộ tuyến tiến hóa của mọi sinh vật, bắt đầu hành trình đỉnh cao.',
  country: 'Trung',
  characters: [
    { name: 'Cao Bằng', role: 'Main Character', description: 'Ngự thú sư sở hữu khả năng nhìn thấu lộ tuyến tiến hóa. Tính cách bình tĩnh, thận trọng và rất yêu thương ngự thú.' },
    { name: 'Đại Tử (Tử Điện Ngô Công)', role: 'Ngự thú đầu tiên', description: 'Con rết khổng lồ mang thuộc tính lôi điện, cực kỳ trung thành và có phần ngốc nghếch.' },
    { name: 'A Tỳ (Huyết Thú)', role: 'Ngự thú', description: 'Sinh vật hệ huyết, có khả năng hồi phục và tấn công cực mạnh.' },
    { name: 'A Ngốc (Cốt Thú)', role: 'Ngự thú', description: 'Bộ xương khô mang sức mạnh thần bí, có khả năng tiến hóa thành Minh Vương.' },
    { name: 'Tiểu Hoa (Thiên Diệp Thanh Đằng)', role: 'Ngự thú', description: 'Thực vật biến dị, có khả năng khống chế và trị thương.' },
    { name: 'A Bàn (Địa Bàn Hùng)', role: 'Ngự thú', description: 'Con gấu khổng lồ với sức mạnh phòng ngự tuyệt đối.' },
    { name: 'Kim Tiền Báo', role: 'Ngự thú', description: 'Tốc độ cực nhanh, sát thủ trong rừng rậm.' },
    { name: 'Bạch Long', role: 'Ngự thú huyền thoại', description: 'Rồng trắng mang sức mạnh ánh sáng, biểu tượng của sự cao quý.' },
    { name: 'Kỷ Hàn Vũ', role: 'Ông ngoại Cao Bằng', description: 'Một trong những ngự thú sư mạnh nhất thế giới, người bảo hộ cho Cao Bằng.' },
    { name: 'Cao Hải', role: 'Cha Cao Bằng', description: 'Nhà nghiên cứu mất tích, để lại nhiều bí ẩn cho Cao Bằng.' },
    { name: 'Lưu Quân', role: 'Bạn thân Cao Bằng', description: 'Ngự thú sư hệ hỏa, tính cách nhiệt tình, thẳng thắn.' },
    { name: 'Trần Tuyết', role: 'Bạn học Cao Bằng', description: 'Cô gái xinh đẹp, sở hữu ngự thú hệ băng.' },
    { name: 'Lão hiệu trưởng', role: 'Người dẫn dắt', description: 'Hiệu trưởng trường ngự thú, luôn ủng hộ tài năng của Cao Bằng.' },
    { name: 'Mục Thiết', role: 'Đối thủ ban đầu', description: 'Thiên tài ngự thú, luôn muốn so tài cao thấp với Cao Bằng.' },
    { name: 'Tần gia chủ', role: 'Thế lực đối địch', description: 'Người luôn tìm cách hãm hại gia đình Cao Bằng.' },
    { name: 'Hàn Sương', role: 'Nữ ngự thú sư mạnh mẽ', description: 'Thành viên của tổ chức bảo vệ nhân loại.' },
    { name: 'Lý Thanh', role: 'Nhà nghiên cứu ngự thú', description: 'Người giúp Cao Bằng hiểu rõ hơn về các loại quái vật.' },
    { name: 'Vương Đại Lực', role: 'Ngự thú sư tự do', description: 'Người có kinh nghiệm chiến đấu phong phú.' },
    { name: 'Triệu Linh', role: 'Cô gái bí ẩn', description: 'Sở hữu ngự thú có khả năng tiên tri.' },
    { name: 'Hắc Y Nhân', role: 'Kẻ thù bí ẩn', description: 'Thành viên của tổ chức muốn hủy diệt thế giới.' },
    { name: 'A Thất', role: 'Ngự thú hệ ám', description: 'Sinh vật bóng đêm, cực kỳ khó lường.' },
    { name: 'Tiểu Thanh', role: 'Ngự thú chim xanh', description: 'Khả năng bay lượn và trinh sát tuyệt vời.' },
    { name: 'Đại Thiết', role: 'Ngự thú hệ kim loại', description: 'Cỗ máy chiến đấu thực thụ.' },
    { name: 'Lão Trương', role: 'Người bán ngự thú', description: 'Khách quen của Cao Bằng, cung cấp nhiều thông tin hữu ích.' },
    { name: 'Tô Mạt', role: 'Thiên tài ngự thú phương Nam', description: 'Cô gái có phong cách chiến đấu hoa mỹ.' },
    { name: 'Lâm Phong', role: 'Ngự thú sư hệ phong', description: 'Tốc độ là vũ khí mạnh nhất của anh ta.' },
    { name: 'Diệp Tử', role: 'Em gái Trần Tuyết', description: 'Cô bé đáng yêu, rất thích Đại Tử.' },
    { name: 'Vương Hổ', role: 'Ngự thú sư hệ thổ', description: 'Sức mạnh cơ bắp kết hợp với ngự thú khổng lồ.' },
    { name: 'Chu Hải', role: 'Nhà thám hiểm', description: 'Người thường xuyên đi vào các vùng cấm.' },
    { name: 'Mã Lực', role: 'Ngự thú sư hệ lôi', description: 'Sức mạnh tấn công bùng nổ.' },
    { name: 'Hà Linh', role: 'Nữ y tá ngự thú', description: 'Chuyên gia chữa trị cho các ngự thú bị thương.' },
    { name: 'Tôn Kiên', role: 'Đội trưởng đội an ninh', description: 'Người có trách nhiệm cao, bảo vệ thành phố.' },
    { name: 'Lý Na', role: 'Phóng viên ngự thú', description: 'Luôn theo sát các trận đấu của Cao Bằng.' },
    { name: 'Trương Ba', role: 'Ngự thú sư hệ độc', description: 'Cách chiến đấu quỷ dị, khó phòng bị.' },
    { name: 'Phạm Tiến', role: 'Nhà sưu tầm ngự thú', description: 'Người sở hữu nhiều loại ngự thú quý hiếm.' },
    { name: 'Đỗ Quyên', role: 'Nữ ngự thú sư hệ hoa', description: 'Vẻ đẹp đi kèm với sự nguy hiểm.' },
    { name: 'Tạ Thiên', role: 'Thiên tài ngự thú phương Bắc', description: 'Đối thủ lớn nhất của Cao Bằng trong các giải đấu.' },
    { name: 'Lục Bình', role: 'Ngự thú sư hệ thủy', description: 'Khả năng khống chế dòng nước điêu luyện.' },
    { name: 'Thần Thú Ý Chí', role: 'Thực thể cổ đại', description: 'Ý chí của các vị thần thú, hướng dẫn Cao Bằng tiến hóa.' },
    { name: 'Cao Bằng (Tương lai)', role: 'Thần Ngự Thú', description: 'Hình ảnh Cao Bằng khi đã đạt đến đỉnh cao, thống trị muôn thú.' }
  ]
};
