
import { FanficWork } from '../types';

export const tinhGiapHonTuong: FanficWork = {
  id: 'tinh_giap_hon_tuong',
  title: 'Tinh Giáp Hồn Tướng',
  description: 'Thế giới tương lai nơi con người chiến đấu bằng các bộ giáp Tinh Giáp kết hợp với linh hồn của các danh tướng lịch sử. Hạ Hầu Đôn vô tình thức tỉnh hệ thống Hồn Tướng, bắt đầu hành trình thống nhất các tinh hệ.',
  country: 'Trung',
  characters: [
    { name: 'Hạ Hầu Đôn', role: 'Main Character', description: 'Người sở hữu hệ thống Hồn Tướng, có khả năng triệu hoán linh hồn các danh tướng Tam Quốc. Tính cách mạnh mẽ, quyết đoán và trọng tình nghĩa.' },
    { name: 'Tào Tháo', role: 'Hồn Tướng (Lãnh đạo)', description: 'Linh hồn của Ngụy Vương, người cố vấn chiến lược và cung cấp sức mạnh uy áp cho Hạ Hầu Đôn.' },
    { name: 'Quan Vũ', role: 'Hồn Tướng (Chiến thần)', description: 'Linh hồn của Võ Thánh, mang lại sức mạnh tấn công tuyệt đối và lòng trung nghĩa.' },
    { name: 'Triệu Vân', role: 'Hồn Tướng (Tốc độ)', description: 'Linh hồn của Thường Sơn Triệu Tử Long, mang lại khả năng phản xạ và tốc độ kinh người.' },
    { name: 'Lữ Bố', role: 'Hồn Tướng (Hủy diệt)', description: 'Linh hồn của Chiến Thần mạnh nhất, sức mạnh phá hoại vô song nhưng khó kiểm soát.' },
    { name: 'Gia Cát Lượng', role: 'Hồn Tướng (Trí tuệ)', description: 'Linh hồn của Ngọa Long, người điều khiển các trận pháp và chiến thuật không gian.' },
    { name: 'Chu Du', role: 'Hồn Tướng (Hỏa diệt)', description: 'Linh hồn của Mỹ Chu Lang, mang lại sức mạnh thiêu rụi mọi kẻ thù.' },
    { name: 'Điêu Thuyền', role: 'Hồn Tướng (Mị hoặc)', description: 'Linh hồn của mỹ nhân, có khả năng khống chế tâm trí và hỗ trợ tinh thần.' },
    { name: 'Tôn Thượng Hương', role: 'Hồn Tướng (Xạ thủ)', description: 'Linh hồn của Kiêu Cơ, mang lại khả năng tấn công tầm xa chính xác.' },
    { name: 'Trương Phi', role: 'Hồn Tướng (Uy áp)', description: 'Linh hồn của Dực Đức, tiếng gầm làm rung chuyển cả tinh hệ.' },
    { name: 'Lâm Tuyết', role: 'Nữ chính (Phi công)', description: 'Thiên tài lái Tinh Giáp, bạn đồng hành và là người yêu của Hạ Hầu Đôn.' },
    { name: 'Vương Đại Lực', role: 'Bạn thân (Kỹ thuật)', description: 'Chuyên gia sửa chữa và nâng cấp Tinh Giáp, luôn hỗ trợ Hạ Hầu Đôn.' },
    { name: 'Diệp Linh', role: 'Nữ đặc vụ (Liên Minh)', description: 'Người giám sát Hạ Hầu Đôn, ban đầu nghi ngờ sau đó trở thành đồng minh.' },
    { name: 'Hắc Y Nhân', role: 'Kẻ thù bí ẩn (Ám Tinh)', description: 'Thành viên của tổ chức muốn lợi dụng Hồn Tướng để thống trị vũ trụ.' },
    { name: 'Lý Thanh', role: 'Nhà khoa học (Hồn Tướng)', description: 'Người nghiên cứu về sự kết hợp giữa công nghệ và linh hồn.' },
    { name: 'Triệu Linh', role: 'Nữ bác sĩ (Quân y)', description: 'Chuyên gia chữa trị các vết thương linh hồn cho các phi công.' },
    { name: 'Mục Thiết', role: 'Đối thủ (Tinh hệ khác)', description: 'Người sở hữu Hồn Tướng của các danh tướng phương Tây.' },
    { name: 'Tần gia chủ', role: 'Thế lực tài phiệt', description: 'Người nắm giữ nguồn tài nguyên Tinh Thạch khổng lồ.' },
    { name: 'Hàn Sương', role: 'Nữ chiến binh (Cơ giới)', description: 'Người có cơ thể được nâng cấp bằng công nghệ nano.' },
    { name: 'Hạ Hầu Hải', role: 'Cha Hạ Hầu Đôn', description: 'Nhà nghiên cứu mất tích, người đầu tiên khám phá ra bí mật Hồn Tướng.' },
    { name: 'Vương Hổ', role: 'Đội trưởng an ninh', description: 'Sức mạnh cơ bắp kết hợp với Tinh Giáp hạng nặng.' },
    { name: 'Chu Hải', role: 'Nhà thám hiểm không gian', description: 'Người thường xuyên đi vào các vùng tinh vân nguy hiểm.' },
    { name: 'Mã Lực', role: 'Chiến binh hệ lôi', description: 'Sức mạnh tấn công bùng nổ từ Tinh Giáp điện năng.' },
    { name: 'Hà Linh', role: 'Nữ y tá (Tâm linh)', description: 'Người có khả năng làm dịu sự hỗn loạn của linh hồn.' },
    { name: 'Tôn Kiên', role: 'Chỉ huy hạm đội', description: 'Người có trách nhiệm cao, bảo vệ tinh hệ quê hương.' },
    { name: 'Lý Na', role: 'Phóng viên chiến trường', description: 'Luôn theo sát các trận chiến của Hạ Hầu Đôn.' },
    { name: 'Trương Ba', role: 'Chiến binh hệ độc', description: 'Cách chiến đấu quỷ dị, sử dụng Tinh Giáp ăn mòn.' },
    { name: 'Phạm Tiến', role: 'Nhà sưu tầm Tinh Giáp', description: 'Người sở hữu bộ sưu tập Tinh Giáp cổ đại khổng lồ.' },
    { name: 'Đỗ Quyên', role: 'Nữ chiến binh hệ hoa', description: 'Vẻ đẹp đi kèm với sự nguy hiểm từ Tinh Giáp sinh học.' },
    { name: 'Tạ Thiên', role: 'Thiên tài Tinh Giáp phương Bắc', description: 'Đối thủ lớn nhất của Hạ Hầu Đôn.' },
    { name: 'Lục Bình', role: 'Chiến binh hệ thủy', description: 'Khả năng khống chế Tinh Giáp chất lỏng.' },
    { name: 'Thần Hồn Ý Chí', role: 'Thực thể cổ đại', description: 'Ý chí của các danh tướng, hướng dẫn Hạ Hầu Đôn.' },
    { name: 'Hạ Hầu Đôn (Tương lai)', role: 'Vũ Trụ Chi Chủ', description: 'Hình ảnh Hạ Hầu Đôn khi đã thống nhất toàn bộ vũ trụ.' },
    { name: 'Tiểu Hắc', role: 'Robot hỗ trợ', description: 'Robot thông minh có khả năng phân tích dữ liệu chiến đấu.' },
    { name: 'Bạch Lão', role: 'Người gác cổng tinh hệ', description: 'Người canh giữ lối vào các vùng không gian cấm.' },
    { name: 'Thanh Nữ', role: 'Thực thể linh hồn', description: 'Cô gái được tạo ra từ năng lượng Hồn Tướng thuần khiết.' },
    { name: 'Hồng Ma', role: 'Kẻ hủy diệt tinh hệ', description: 'Thực thể mang sức mạnh hỗn loạn.' },
    { name: 'Lam Thần', role: 'Người bảo hộ trật tự', description: 'Thực thể mang sức mạnh cân bằng.' },
    { name: 'Tử Vương', role: 'Kẻ thống trị hư vô', description: 'Thực thể mang sức mạnh bóng tối.' },
    { name: 'Kim Thánh', role: 'Người mang ánh sáng sáng tạo', description: 'Thực thể mang sức mạnh khởi nguyên.' }
  ]
};
