import { FanficWork } from '../types';

export const toanChucCaoThu: FanficWork = {
  id: 'toan-chuc-cao-thu',
  title: 'Toàn Chức Cao Thủ',
  description: 'Diệp Tu, một cao thủ đứng đầu trò chơi Vinh Quang, bị câu lạc bộ ép giải nghệ nhưng đã trở lại từ con số không tại một tiệm net.',
  country: 'Trung',
  plot: 'Diệp Tu được mệnh danh là "Đấu Thần" trong trò chơi Vinh Quang, nhưng vì mâu thuẫn với câu lạc bộ, anh bị ép phải giải nghệ và để lại tài khoản huyền thoại Nhất Diệp Chi Thu. Anh trở thành nhân viên trông net ca đêm và bắt đầu lại với tài khoản mới mang tên Quân Mạc Tiếu tại máy chủ thứ 10, sử dụng món vũ khí tự chế Ô Thiên Cơ để khuấy đảo giới chuyên nghiệp một lần nữa.',
  worldSetting: 'Thế giới game eSports chuyên nghiệp với trò chơi Vinh Quang. Hệ thống nghề nghiệp đa dạng và kỹ năng thao tác cực cao là yếu tố quyết định chiến thắng.',
  characters: [
    { name: 'Diệp Tu', role: 'Nhân vật chính', age: '25-28', description: 'Bậc thầy chiến thuật, "Đấu Thần" của Vinh Quang. Anh là một người điềm tĩnh, có phần "vô sỉ" trong game nhưng cực kỳ tâm huyết với eSports.' },
    { name: 'Trần Quả', role: 'Đồng minh / Chủ tiệm net', age: '27-30', description: 'Chủ tiệm net Hưng Hân, một người phụ nữ mạnh mẽ, nhiệt tình và là fan cuồng của Diệp Tu. Cô là người đã hỗ trợ anh thành lập chiến đội Hưng Hân.' },
    { name: 'Đường Nhu', role: 'Đồng minh / Chiến binh', age: '21-23', description: 'Một thiên tài piano với ý chí chiến đấu cực cao. Cô được Diệp Tu dẫn dắt vào Vinh Quang và trở thành một pháp sư chiến đấu mạnh mẽ.' },
    { name: 'Tô Mộc Tranh', role: 'Nữ chính / Bậc thầy pháo súng', age: '23-25', description: 'Đồng đội ăn ý nhất của Diệp Tu, em gái của Tô Mộc Thu. Cô là một trong những tuyển thủ chuyên nghiệp hàng đầu và luôn ủng hộ Diệp Tu vô điều kiện.' },
    { name: 'Bao Vinh Hưng (Bao Tử)', role: 'Đồng minh / Lưu manh', age: '23-25', description: 'Một người chơi có lối đánh kỳ lạ, khó lường và tính cách vô tư. Anh là một thành viên quan trọng và trung thành của chiến đội Hưng Hân.' },
    { name: 'Kiều Nhất Phàm', role: 'Đồng minh / Trận quỷ', age: '18-20', description: 'Từng bị coi là người thừa ở Vi Thảo, nhưng sau khi được Diệp Tu chỉ dẫn, anh đã tìm thấy bản thân trong vai trò Trận quỷ và trở thành bộ não thứ hai của Hưng Hân.' },
    { name: 'La Tập', role: 'Đồng minh / Pháp sư triệu hồi', age: '19-21', description: 'Một sinh viên toán học thiên tài, sử dụng các phép tính logic để điều khiển triệu hồi thú. Dù thao túng còn yếu nhưng chiến thuật của anh rất đáng sợ.' },
    { name: 'Mạc Phàm', role: 'Đồng minh / Ninja', age: '20-22', description: 'Một "kẻ lượm mót" nổi tiếng trong game với lối đánh đơn độc. Sau khi gia nhập Hưng Hân, anh đã học được cách phối hợp và trở thành một sát thủ đáng gờm.' },
    { name: 'Ngụy Sâm', role: 'Đồng minh / Thuật sĩ', age: '30-32', description: 'Cựu đội trưởng Lam Vũ, một lão tướng "vô sỉ" không kém Diệp Tu. Anh mang theo tài khoản Sách Khắc Tát Nhĩ và kinh nghiệm dày dặn để giúp sức cho Hưng Hân.' },
    { name: 'An Văn Dật', role: 'Đồng minh / Mục sư', age: '20-22', description: 'Một người chơi lý trí tuyệt đối, luôn tính toán thời điểm hồi máu chính xác nhất. Dù thao tác không nhanh nhưng anh là mảnh ghép không thể thiếu của đội.' },
    { name: 'Hàn Văn Thanh', role: 'Đối thủ / Nhà quyền pháp', age: '26-29', description: 'Đội trưởng chiến đội Bá Đồ, đối thủ truyền kiếp của Diệp Tu. Anh là biểu tượng của sự kiên trì và lối đánh tấn công mãnh liệt.' },
    { name: 'Dụ Văn Châu', role: 'Đối thủ / Thuật sĩ', age: '24-26', description: 'Đội trưởng chiến đội Lam Vũ, một bậc thầy chiến thuật với tốc độ tay chậm nhưng trí tuệ siêu việt.' },
    { name: 'Hoàng Thiếu Thiên', role: 'Đối thủ / Kiếm khách', age: '23-25', description: 'Chủ lực của Lam Vũ, được mệnh danh là "Kiếm Thánh". Anh nổi tiếng với khả năng chớp thời cơ và cái miệng không bao giờ ngừng nói.' },
    { name: 'Vương Kiệt Hi', role: 'Đối thủ / Ma đạo học giả', age: '25-27', description: 'Đội trưởng chiến đội Vi Thảo, được gọi là "Ma Thuật Sư" vì lối đánh biến ảo khôn lường.' },
    { name: 'Chu Trạch Khải', role: 'Đối thủ / Thiện xạ', age: '22-24', description: 'Đội trưởng chiến đội Luân Hồi, "Đệ nhất nhân" hiện tại của Vinh Quang với kỹ năng cá nhân hoàn hảo và vẻ ngoài điển trai.' },
    { name: 'Tô Mộc Thu', role: 'Huyền thoại / Bạn thân', age: '18 (khi mất)', description: 'Anh trai của Tô Mộc Tranh, bạn thân nhất của Diệp Tu. Anh là thiên tài đã chế tạo ra Ô Thiên Cơ nhưng không may qua đời sớm.' },
    { name: 'Diệp Thu', role: 'Gia đình', age: '25-28', description: 'Em trai sinh đôi của Diệp Tu, một doanh nhân thành đạt. Anh thường xuyên bị Diệp Tu mượn danh tính để thi đấu chuyên nghiệp.' },
    { name: 'Tôn Tường', role: 'Đối thủ / Pháp sư chiến đấu', age: '20-22', description: 'Người kế thừa tài khoản Nhất Diệp Chi Thu tại Gia Thế. Anh là một thiên tài kiêu ngạo nhưng sau này đã trưởng thành hơn tại Luân Hồi.' },
    { name: 'Lưu Hạo', role: 'Phản diện / Kiếm khách ma pháp', age: '23-25', description: 'Cựu phó đội trưởng Gia Thế, kẻ luôn âm mưu hãm hại Diệp Tu vì sự đố kỵ và tham vọng cá nhân.' },
    { name: 'Cao Anh Kiệt', role: 'Đối thủ / Ma đạo học giả', age: '17-19', description: 'Thiên tài trẻ tuổi của Vi Thảo, người được Vương Kiệt Hi chọn làm người kế thừa vị trí chủ lực của đội.' },
    { name: 'Lư Hãn Văn', role: 'Đối thủ / Kiếm khách', age: '14-16', description: 'Thành viên nhỏ tuổi nhất của Lam Vũ, một thiên tài kiếm đạo với tinh thần lạc quan và ý chí chiến đấu mạnh mẽ.' },
    { name: 'Đường Hạo', role: 'Đối thủ / Lưu manh', age: '21-23', description: 'Đội trưởng Hô Khiếu, người đã đánh bại Lâm Kính Ngôn để trở thành "Đệ nhất lưu manh" mới của Vinh Quang.' },
    { name: 'Phương Duệ', role: 'Đồng minh / Khí công sư', age: '23-25', description: 'Bậc thầy "đánh bẩn" của Vinh Quang. Sau khi rời Hô Khiếu, anh gia nhập Hưng Hân và chuyển sang chơi Khí công sư.' },
    { name: 'Lâm Kính Ngôn', role: 'Đối thủ / Lưu manh', age: '26-28', description: 'Cựu đội trưởng Hô Khiếu, một lão tướng điềm đạm. Sau khi bị Đường Hạo thay thế, anh gia nhập Bá Đồ để tìm kiếm vinh quang cuối cùng.' },
    { name: 'Trương Tân Kiệt', role: 'Đối thủ / Mục sư', age: '24-26', description: 'Phó đội trưởng Bá Đồ, một trong "Bốn bậc thầy chiến thuật". Anh nổi tiếng với lối sống kỷ luật và khả năng hồi máu chính xác đến từng giây.' },
    { name: 'Trương Giai Lạc', role: 'Đối thủ / Chuyên gia đạn dược', age: '25-27', description: 'Cựu đội trưởng Bách Hoa, người đã ba lần về nhì tại giải chuyên nghiệp. Anh gia nhập Bá Đồ với khát khao cháy bỏng giành chức vô địch.' },
    { name: 'Giang Ba Đào', role: 'Đối thủ / Kiếm khách ma pháp', age: '22-24', description: 'Phó đội trưởng Luân Hồi, người được mệnh danh là "Chất kết dính" giúp Chu Trạch Khải tỏa sáng rực rỡ nhất.' },
    { name: 'Tiêu Thời Khâm', role: 'Đối thủ / Kỹ sư máy móc', age: '24-26', description: 'Đội trưởng Lôi Đình, một trong "Bốn bậc thầy chiến thuật". Anh nổi tiếng với khả năng tận dụng tối đa sức mạnh của các thành viên trong đội.' },
    { name: 'Hứa Bác Viễn (Lam Hà)', role: 'Đồng minh / Kiếm khách', age: '22-24', description: 'Trưởng công hội Lam Khê Các tại máy chủ thứ 10. Anh thường xuyên bị Diệp Tu "hành hạ" nhưng cũng rất nể phục tài năng của anh.' },
    { name: 'Ngũ Thần', role: 'Đồng minh / Bậc thầy pháo súng', age: '25-27', description: 'Cựu đội trưởng chiến đội Vô Cực. Sau khi đội giải thể, anh gia nhập Hưng Hân và quản lý công hội của đội.' },
    { name: 'Lâm Kính Ngôn (Bá Đồ)', role: 'Đối thủ / Lưu manh', age: '26-28', description: 'Lão tướng điềm đạm, sau khi rời Hô Khiếu đã gia nhập Bá Đồ để cùng các lão tướng khác tìm kiếm chức vô địch.' },
    { name: 'Phương Duệ (Hưng Hân)', role: 'Đồng minh / Khí công sư', age: '23-25', description: 'Bậc thầy "đánh bẩn", sau khi gia nhập Hưng Hân đã chuyển sang Khí công sư và trở thành một phần quan trọng của đội.' },
    { name: 'Trương Giai Lạc (Bá Đồ)', role: 'Đối thủ / Chuyên gia đạn dược', age: '25-27', description: 'Người mang khát khao vô địch mãnh liệt, gia nhập Bá Đồ và tạo nên phong cách chiến đấu "Bách Hoa Liễu Loạn" rực rỡ.' },
    { name: 'Tôn Triết Bình', role: 'Đồng minh / Cuồng kiếm sĩ', age: '26-28', description: 'Cựu đội trưởng Bách Hoa, người sở hữu lối đánh cuồng bạo. Anh đã hỗ trợ Hưng Hân trong vòng loại chuyên nghiệp.' },
    { name: 'Lâu Quan Ninh', role: 'Đồng minh / Cuồng kiếm sĩ', age: '22-24', description: 'Đội trưởng chiến đội Nghĩa Trảm, một thiếu gia giàu có nhưng cực kỳ nghiêm túc với đam mê Vinh Quang.' },
    { name: 'Diệp Tu (Quân Mạc Tiếu)', role: 'Nhân vật chính', age: '25-28', description: 'Danh tính thực sự của người điều khiển Quân Mạc Tiếu, người đã dẫn dắt Hưng Hân từ quán net đến chức vô địch thế giới.' },
    { name: 'Tô Mộc Tranh (Mộc Vũ Tranh Phong)', role: 'Nữ chính', age: '23-25', description: 'Nữ thần của Vinh Quang, người luôn sát cánh cùng Diệp Tu trong mọi trận chiến.' },
    { name: 'Đường Nhu (Hàn Yên Nhu)', role: 'Đồng minh', age: '21-23', description: 'Ý chí sắt đá, luôn tiến về phía trước với những cú đâm mâu đầy uy lực.' },
    { name: 'Bao Vinh Hưng (Bánh Bao Xâm Chiếm)', role: 'Đồng minh', age: '23-25', description: 'Lối đánh không theo quy luật, luôn khiến đối thủ phải đau đầu suy đoán.' },
    { name: 'Kiều Nhất Phàm (Một Inch Tro)', role: 'Đồng minh', age: '18-20', description: 'Bậc thầy khống chế trận địa, người thầm lặng cống hiến cho chiến thắng của đội.' },
    { name: 'La Tập (Muội Quang)', role: 'Đồng minh', age: '19-21', description: 'Sử dụng toán học để tối ưu hóa sức mạnh triệu hồi, một thiên tài chiến thuật trẻ tuổi.' },
    { name: 'An Văn Dật (Tay Nhỏ Lạnh Lẽo)', role: 'Đồng minh', age: '20-22', description: 'Mục sư với khả năng tính toán thời điểm cứu nguy cực kỳ chính xác.' },
    { name: 'Mạc Phàm (Hại Người Không Mệt)', role: 'Đồng minh', age: '20-22', description: 'Sát thủ ninja với khả năng bùng nổ sát thương trong thời gian ngắn.' },
    { name: 'Ngụy Sâm (Nghênh Phong Bố Trận)', role: 'Đồng minh', age: '30-32', description: 'Lão tướng với những cái bẫy thuật sĩ đầy mưu mô và kinh nghiệm dày dặn.' },
    { name: 'Trần Quả (Trục Yên Hà)', role: 'Đồng minh', age: '27-30', description: 'Bà chủ của Hưng Hân, người đã đặt nền móng cho sự trở lại của một huyền thoại.' },
    { name: 'Tiêu Thời Khâm (Diệt Sinh Linh)', role: 'Đối thủ', age: '24-26', description: 'Bậc thầy máy móc, người luôn tìm ra sơ hở của đối phương thông qua những tính toán chi tiết.' },
    { name: 'Vương Kiệt Hi (Vương Bất Lưu Hành)', role: 'Đối thủ', age: '25-27', description: 'Ma thuật sư bay lượn trên bầu trời, biểu tượng của sự biến ảo.' },
    { name: 'Dụ Văn Châu (Sách Khắc Tát Nhĩ)', role: 'Đối thủ', age: '24-26', description: 'Người điều khiển bóng tối, dùng trí tuệ để bù đắp cho tốc độ tay.' },
    { name: 'Hoàng Thiếu Thiên (Dạ Vũ Thanh Phiền)', role: 'Đối thủ', age: '23-25', description: 'Kiếm thánh với những lời thoại gây nhiễu loạn và những nhát kiếm chí mạng.' },
    { name: 'Chu Trạch Khải (Nhất Thương Xuyên Vân)', role: 'Đối thủ', age: '22-24', description: 'Súng vương với kỹ năng hoa mỹ và hiệu quả bậc nhất Vinh Quang.' },
    { name: 'Hàn Văn Thanh (Đại Mạc Cô Yên)', role: 'Đối thủ', age: '26-29', description: 'Quyền hoàng với ý chí thép, không bao giờ lùi bước trước bất kỳ đối thủ nào.' }
  ]
};
